# Generated by Django 4.2.28 on 2026-05-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GO', '0170_rdo_data_analise_ia_rdo_erro_analise_ia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RDO_SEM_TURNO', 'RDO sem turno'), ('RDO_DATA_PULADA', 'RDO com data pulada na sequencia'), ('PT_SEM_TURNO', 'PT sem turno informado'), ('PT_SEM_NUMERO', 'PT sem número'), ('PT_INCOERENTE', 'PT incoerente'), ('ATIVIDADE_SEM_HORARIO', 'Atividade sem horário'), ('ATIVIDADE_SOBREPOSTA', 'Atividades sobrepostas'), ('ESPACO_CONFINADO_SEM_HORARIO', 'Espaço confinado sem horário'), ('ESPACO_CONFINADO_INCOERENTE', 'Espaço confinado incoerente'), ('OPERADORES_MAIOR_EQUIPE', 'Operadores maior que equipe'), ('VALOR_DIARIO_MAIOR_PREVISAO', 'Valor diário maior que previsão'), ('AVANCO_INVALIDO', 'Avanço inválido'), ('FOTO_AUSENTE', 'Foto ausente'), ('OBSERVACAO_INCOERENTE', 'Observação incoerente')], max_length=100)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('equipe_responsavel', models.CharField(choices=[('operacao', 'Operação'), ('coordenacao', 'Coordenação'), ('qsms', 'QSMS'), ('administrativo', 'Administrativo')], default='operacao', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado com justificativa')], default='pendente', max_length=30)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_inteligentes', to='GO.rdo')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='alertas_int_status_be61b0_idx'), models.Index(fields=['tipo'], name='alertas_int_tipo_62848b_idx'), models.Index(fields=['prioridade'], name='alertas_int_priorid_2a6cc6_idx'), models.Index(fields=['equipe_responsavel'], name='alertas_int_equipe__4025b4_idx')],
            },
        ),
    ]
