# Generated by Django 4.2.28 on 2026-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_inteligentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertainteligente',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='alertainteligente',
            index=models.Index(fields=['referencia'], name='alertas_int_referen_c9703f_idx'),
        ),
    ]
