# Generated by Django 4.2.28 on 2026-05-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas_inteligentes', '0002_alertainteligente_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertainteligente',
            name='ignorado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_ignorados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertainteligente',
            name='resolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
