# Generated by Django 4.2.28 on 2026-05-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0171_rdo_data_pendente_analise_ia'),
        ('alertas_inteligentes', '0003_alertainteligente_ignorado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaOperacionalInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OS_SEM_RDO_RECENTE', 'OS em andamento sem RDO recente'), ('OS_PROGRAMADA_ATRASADA', 'OS programada atrasada'), ('OS_FINALIZADA_MOVIMENTACAO_ABERTA', 'OS finalizada com movimentação aberta'), ('OPERACAO_SEM_DATA_INICIO', 'Operação sem data de início'), ('OS_SEM_SUPERVISOR', 'Os em andamento sem supervisor'), ('MOVIMENTACAO_SEM_DATA', 'Movimentação sem data'), ('SUPERVISOR_EM_OS_SIMULTANEAS', 'Supervisor em OS simultâneas'), ('POUCOS_RDOS_PARA_DIAS_OPERACAO', 'Poucos RDOs para dias de operação')], max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('ignorado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_operacionais_ignorados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_operacionais_ia', to='GO.ordemservico')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_operacionais_resolvidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status'], name='alertas_int_status_66a69c_idx'), models.Index(fields=['tipo'], name='alertas_int_tipo_8ecbcd_idx'), models.Index(fields=['prioridade'], name='alertas_int_priorid_9819a0_idx'), models.Index(fields=['referencia'], name='alertas_int_referen_576edf_idx')],
            },
        ),
    ]
