# Generated by Django 4.2.28 on 2026-05-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas_inteligentes', '0004_alertaoperacionalinteligente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemploIntencaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField()),
                ('frase_normalizada', models.TextField(db_index=True)),
                ('intencao', models.CharField(choices=[('consulta_os', 'Consulta de OS'), ('consulta_rdo', 'Consulta de RDO'), ('consulta_supervisor', 'Consulta de supervisor'), ('resumo_os', 'Resumo de OS'), ('linha_tempo_os', 'Linha do tempo da OS'), ('comparacao_rdos', 'Comparacao entre RDOs'), ('operacao_parada', 'Operacao parada'), ('analise_supervisor', 'Analise de supervisor'), ('analise_unidade', 'Analise de unidade'), ('priorizacao', 'Prioridades'), ('resumo_diario', 'Resumo diario'), ('os_sem_rdo_recente', 'OS sem RDO recente'), ('supervisores_conflito', 'Supervisores em conflito'), ('pendencias_gerais', 'Pendencias gerais')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemplos_intencao_ia_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AlterField(
            model_name='alertaoperacionalinteligente',
            name='tipo',
            field=models.CharField(choices=[('OS_SEM_RDO_RECENTE', 'OS em andamento sem RDO recente'), ('SUPERVISOR_EM_OS_SIMULTANEAS', 'Supervisor em OS simultâneas'), ('OS_SEM_SUPERVISOR', 'Os em andamento sem supervisor'), ('OS_FINALIZADA_MOVIMENTACAO_ABERTA', 'OS finalizada com movimentação aberta'), ('OS_PROGRAMADA_ATRASADA', 'OS programada atrasada'), ('POUCOS_RDOS_PARA_DIAS_OPERACAO', 'Poucos RDOs para dias de operação'), ('OPERACAO_SEM_DATA_INICIO', 'Operação sem data de início'), ('MOVIMENTACAO_SEM_DATA', 'Movimentação sem data')], max_length=100),
        ),
        migrations.CreateModel(
            name='PerguntaAssistenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('pergunta_normalizada', models.TextField(db_index=True)),
                ('intencao_detectada', models.CharField(blank=True, choices=[('consulta_os', 'Consulta de OS'), ('consulta_rdo', 'Consulta de RDO'), ('consulta_supervisor', 'Consulta de supervisor'), ('resumo_os', 'Resumo de OS'), ('linha_tempo_os', 'Linha do tempo da OS'), ('comparacao_rdos', 'Comparacao entre RDOs'), ('operacao_parada', 'Operacao parada'), ('analise_supervisor', 'Analise de supervisor'), ('analise_unidade', 'Analise de unidade'), ('priorizacao', 'Prioridades'), ('resumo_diario', 'Resumo diario'), ('os_sem_rdo_recente', 'OS sem RDO recente'), ('supervisores_conflito', 'Supervisores em conflito'), ('pendencias_gerais', 'Pendencias gerais')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('entendida', 'Entendida'), ('nao_entendida', 'Nao entendida'), ('revisada', 'Revisada')], default='nao_entendida', max_length=20)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('revisada_em', models.DateTimeField(blank=True, null=True)),
                ('exemplo_aprovado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_origem', to='alertas_inteligentes.exemplointencaoia')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_ia_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
