# Generated by Django 4.2.28 on 2026-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_inteligentes', '0005_exemplointencaoia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplointencaoia',
            name='frase_normalizada',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
