# Generated by Django 4.2.28 on 2026-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_inteligentes', '0007_alertainteligente_anomaly_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertainteligente',
            name='tipo',
            field=models.CharField(choices=[('RDO_SEM_TURNO', 'RDO sem turno'), ('RDO_DATA_PULADA', 'RDO com data pulada na sequencia'), ('PT_SEM_TURNO', 'PT sem turno informado'), ('PT_SEM_NUMERO', 'PT sem número'), ('PT_INCOERENTE', 'PT incoerente'), ('ATIVIDADE_SEM_HORARIO', 'Atividade sem horário'), ('ATIVIDADE_SOBREPOSTA', 'Atividades sobrepostas'), ('ESPACO_CONFINADO_SEM_HORARIO', 'Espaço confinado sem horário'), ('ESPACO_CONFINADO_INCOERENTE', 'Espaço confinado incoerente'), ('OPERADORES_MAIOR_EQUIPE', 'Operadores maior que equipe'), ('VALOR_DIARIO_MAIOR_PREVISAO', 'Valor diário maior que previsão'), ('AVANCO_INVALIDO', 'Avanço inválido'), ('FOTO_AUSENTE', 'Foto ausente'), ('OBSERVACAO_INCOERENTE', 'Observação incoerente'), ('RDO_OUTLIER', 'RDO com comportamento fora do padrão'), ('RDO_REVISAR_ANOMALIA', 'RDO marcado para revisão estatística'), ('RDO_TANQUE_INCOMPLETO', 'Tanque com dados incompletos no RDO')], max_length=100),
        ),
    ]
