# Generated by Django 4.2.28 on 2026-07-31 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas_inteligentes', '0010_alter_alertainteligente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraAlertaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=True)),
                ('lido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alerta_operacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leituras_usuario', to='alertas_inteligentes.alertaoperacionalinteligente')),
                ('alerta_rdo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leituras_usuario', to='alertas_inteligentes.alertainteligente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_alertas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leitura de alerta da IA',
                'verbose_name_plural': 'leituras de alertas da IA',
                'indexes': [models.Index(fields=['usuario', 'lido'], name='alertas_int_usuario_9a92db_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='leituraalertaia',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('alerta_operacional__isnull', True), ('alerta_rdo__isnull', False)), models.Q(('alerta_operacional__isnull', False), ('alerta_rdo__isnull', True)), _connector='OR'), name='leitura_alerta_ia_uma_origem'),
        ),
        migrations.AddConstraint(
            model_name='leituraalertaia',
            constraint=models.UniqueConstraint(condition=models.Q(('alerta_rdo__isnull', False)), fields=('usuario', 'alerta_rdo'), name='leitura_alerta_ia_usuario_rdo_unique'),
        ),
        migrations.AddConstraint(
            model_name='leituraalertaia',
            constraint=models.UniqueConstraint(condition=models.Q(('alerta_operacional__isnull', False)), fields=('usuario', 'alerta_operacional'), name='leitura_alerta_ia_usuario_oper_unique'),
        ),
    ]
