from django.db import models

# Create your models here.
class OrdemServico(models.Model):
    
    TAG_CHOICES = [
        ('ACO', 'ACO'),
        ('ART', 'ART'),
        ('CAT', 'CAT'),
        ('GFI', 'GFI'),
        ('GFE', 'GFE'),
        ('CAG', 'CAG'),
        ('CAA', 'CAA'),
        ('DER', 'DER'),
        ('DES', 'DES'),
        ('DPE', 'DPE'),
        ('DEQ', 'DEQ'),
        ('DEE', 'DEE'),
        ('EEQ', 'EEQ'),
        ('DBT', 'DBT'),
        ('DLD', 'DLD'),
        ('DEL', 'DEL'),
        ('DAO', 'DAO'),
        ('DCO', 'DCO'),
        ('CPP', 'CPP'),
        ('DRE', 'DRE'),
        ('DPR', 'DPR'),
        ('TST', 'TST'),
        ('EPM', 'EPM'),
        ('FFF', 'FFF'),
        ('ENR', 'ENR'),
        ('STB', 'STB'),
        ('EST', 'EST'),
        ('ERE', 'ERE'),
        ('FAL', 'FAL'),
        ('FAU', 'FAU'),
        ('FCV', 'FCV'),
        ('FCT', 'FCT'),
        ('FEL', 'FEL'),
        ('ENQ', 'ENQ'),
        ('EQC', 'EQC'),
        ('ALP', 'ALP'),
        ('ERS', 'ERS'),
        ('FIR', 'FIR'),
        ('FIN', 'FIN'),
        ('MAO', 'MAO'),
        ('MAT', 'MAT'),
        ('MEC', 'MEC'),
        ('QUI', 'QUI'),
        ('TEC', 'TEC'),
        ('EXT', 'EXT'),
        ('HAT', 'HAT'),
        ('INS', 'INS'),
        ('IBO', 'IBO'),
        ('INV', 'INV'),
        ('DCL', 'DCL'),
        ('DCA', 'DCA'),
        ('LDC', 'LDC'),
        ('LCB', 'LCB'),
        ('LAC', 'LAC'),
        ('LAN', 'LAN'),
        ('APP', 'APP'),
        ('LCF', 'LCF'),
        ('LCC', 'LCC'),
        ('VOI', 'VOI'),
        ('LDD', 'LDD'),
        ('DUT', 'DUT'),
        ('ARC', 'ARC'),
        ('EXC', 'EXC'),
        ('LDL', 'LDL'),
        ('SIL', 'SIL'),
        ('LTA', 'LTA'),
        ('LTB', 'LTB'),
        ('LTC', 'LTC'),
        ('LTD', 'LTD'),
        ('LDR', 'LDR'),
        ('LTL', 'LTL'),
        ('TLA', 'TLA'),
        ('MGO', 'MGO'),
        ('LTO', 'LTO'),
        ('LRD', 'LRD'),
        ('LTS', 'LTS'),
        ('TSE', 'TSE'),
        ('LSL', 'LSL'),
        ('LTR', 'LTR'),
        ('AGP', 'AGP'),
        ('LOD', 'LOD'),
        ('SLU', 'SLU'),
        ('LTG', 'LTG'),
        ('LDV', 'LDV'),
        ('VAS', 'VAS'),
        ('DEC', 'DEC'),
        ('LGE', 'LGE'),
        ('LTP', 'LTP'),
        ('LOE', 'LOE'),
        ('MES', 'MES'),
        ('MOE', 'MOE'),
        ('MOP', 'MOP'),
        ('MPE', 'MPE'),
        ('MDS', 'MDS'),
        ('PIN', 'PIN'),
        ('RAD', 'RAD'),
        ('REL', 'REL'),
        ('RPM', 'RPM'),
        ('SSI', 'SSI'),
        ('SIR', 'SIR'),
        ('SHD', 'SHD'),
        ('SUR', 'SUR'),
        ('TDA', 'TDA'),
        ('TDS', 'TDS'),
        ('TEO', 'TEO'),
        ('VIG', 'VIG'),
    ]

    SERVICO_CHOICES = [
        ("ACOMPANHAMENTO DE FLUSHING OU TRANSFERÊNCIA", "ACOMPANHAMENTO DE FLUSHING OU TRANSFERÊNCIA"),
        ("ARMAZENAMENTO TEMPORÁRIO", "ARMAZENAMENTO TEMPORÁRIO"),
        ("CARRETA DE ARMAZENAMENTO TEMPORÁRIO", "CARRETA DE ARMAZENAMENTO TEMPORÁRIO"),
        ("CERTIFICAÇÃO GAS FIRE", "CERTIFICAÇÃO GAS FIRE"),
        ("CERTIFICAÇÃO GAS FREE", "CERTIFICAÇÃO GAS FREE"),
        ("COLETA E ANÁLISE DA ÁGUA", "COLETA E ANÁLISE DA ÁGUA"),
        ("COLETA E ANÁLISE DO AR", "COLETA E ANÁLISE DO AR"),
        ("DESCARTE DE RESIDUOS", "DESCARTE DE RESIDUOS"),
        ("DESCOMISSIONAMENTO", "DESCOMISSIONAMENTO"),
        ("DESCONTAMINAÇÃO PROFUNDA NA EMBARCAÇÃO", "DESCONTAMINAÇÃO PROFUNDA NA EMBARCAÇÃO"),
        ("DESMOBILIZAÇÃO DE EQUIPAMENTOS", "DESMOBILIZAÇÃO DE EQUIPAMENTOS"),
        ("DESMOBILIZAÇÃO DE PESSOAS", "DESMOBILIZAÇÃO DE PESSOAS"),
        ("DESMOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS", "DESMOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS"),
        ("DESOBSTRUÇÃO", "DESOBSTRUÇÃO"),
        ("DESOBSTRUÇÃO DA LINHA DE DRENAGEM ABERTA", "DESOBSTRUÇÃO DA LINHA DE DRENAGEM ABERTA"),
        ("DIÁRIA DA EQUIPE DE LIMPEZA DE TANQUES", "DIÁRIA DA EQUIPE DE LIMPEZA DE TANQUES"),
        ("DIÁRIA DE AJUDANTE OPERACIONAL", "DIÁRIA DE AJUDANTE OPERACIONAL"),
        ("DIÁRIA DE CONSUMÍVEIS PARA LIMPEZA", "DIÁRIA DE CONSUMÍVEIS PARA LIMPEZA"),
        ("DIÁRIA DE CONSUMÍVEIS PARA PINTURA", "DIÁRIA DE CONSUMÍVEIS PARA PINTURA"),
        ("DIÁRIA DE RESGATISTA", "DIÁRIA DE RESGATISTA"),
        ("DIÁRIA DE SUPERVISOR", "DIÁRIA DE SUPERVISOR"),
        ("DIÁRIA DO TÉCNICO DE SEGURANÇA DO TRABALHO", "DIÁRIA DO TÉCNICO DE SEGURANÇA DO TRABALHO"),
        ("ELABORAÇÃO DO PMOC", "ELABORAÇÃO DO PMOC"),
        ("EMISSÃO DE FREE FOR FIRE", "EMISSÃO DE FREE FOR FIRE"),
        ("ENSACAMENTO E REMOÇÃO", "ENSACAMENTO E REMOÇÃO"),
        ("EQUIPAMENTOS EM STAND BY", "EQUIPAMENTOS EM STAND BY"),
        ("EQUIPE EM STAND BY", "EQUIPE EM STAND BY"),
        ("ESGOTAMENTO DE RESÍDUO", "ESGOTAMENTO DE RESÍDUO"),
        ("FORNECIMENTO DE ALMOXARIFE", "FORNECIMENTO DE ALMOXARIFE"),
        ("FORNECIMENTO DE AUXILIAR OFFSHORE", "FORNECIMENTO DE AUXILIAR OFFSHORE"),
        ("FORNECIMENTO DE CAMINHÃO VÁCUO", "FORNECIMENTO DE CAMINHÃO VÁCUO"),
        ("FORNECIMENTO DE CARRETA TANQUE", "FORNECIMENTO DE CARRETA TANQUE"),
        ("FORNECIMENTO DE ELETRICISTA", "FORNECIMENTO DE ELETRICISTA"),
        ("FORNECIMENTO DE ENGENHEIRO QUÍMICO", "FORNECIMENTO DE ENGENHEIRO QUÍMICO"),
        ("FORNECIMENTO DE EQUIPAMENTOS E CONSUMÍVEIS", "FORNECIMENTO DE EQUIPAMENTOS E CONSUMÍVEIS"),
        ("FORNECIMENTO DE EQUIPE DE ALPINISTA INDUSTRIAL", "FORNECIMENTO DE EQUIPE DE ALPINISTA INDUSTRIAL"),
        ("FORNECIMENTO DE EQUIPE DE RESGATE", "FORNECIMENTO DE EQUIPE DE RESGATE"),
        ("FORNECIMENTO DE IRATA N1 OU N2", "FORNECIMENTO DE IRATA N1 OU N2"),
        ("FORNECIMENTO DE IRATA N3", "FORNECIMENTO DE IRATA N3"),
        ("FORNECIMENTO DE MÃO DE OBRA OPERACIONAL", "FORNECIMENTO DE MÃO DE OBRA OPERACIONAL"),
        ("FORNECIMENTO DE MATERIAIS", "FORNECIMENTO DE MATERIAIS"),
        ("FORNECIMENTO DE MECÂNICO", "FORNECIMENTO DE MECÂNICO"),
        ("FORNECIMENTO DE QUÍMICOS", "FORNECIMENTO DE QUÍMICOS"),
        ("FORNECIMENTO DE TÉCNICO OFFSHORE", "FORNECIMENTO DE TÉCNICO OFFSHORE"),
        ("HORA EXTRA CARRETA TANQUE (APÓS 4H DE FRANQUIA)", "HORA EXTRA CARRETA TANQUE (APÓS 4H DE FRANQUIA)"),
        ("HOTEL, ALIMENTAÇÃO E TRANSFER POR PAX", "HOTEL, ALIMENTAÇÃO E TRANSFER POR PAX"),
        ("INSPEÇÃO DE TANQUE", "INSPEÇÃO DE TANQUE"),
        ("INSPEÇÃO POR BOROSCÓPIO", "INSPEÇÃO POR BOROSCÓPIO"),
        ("INVENTÁRIO, LISTA DE VERIFICAÇÃO E PLANEJAMENTO DOS MATERIAIS A BORDO.", "INVENTÁRIO, LISTA DE VERIFICAÇÃO E PLANEJAMENTO DOS MATERIAIS A BORDO."),
        ("LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR + LAVANDERIA)", "LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR + LAVANDERIA)"),
        ("LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR)", "LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR)"),
        ("LIMPEZA (DUTOS + COIFA)", "LIMPEZA (DUTOS + COIFA)"),
        ("LIMPEZA DA CASA DE BOMBAS", "LIMPEZA DA CASA DE BOMBAS"),
        ("LIMPEZA DE AGUAS CINZAS", "LIMPEZA DE AGUAS CINZAS"),
        ("LIMPEZA DE AGUAS NEGRAS", "LIMPEZA DE AGUAS NEGRAS"),
        ("LIMPEZA DE ÁREA DO PISO DE PRAÇA", "LIMPEZA DE ÁREA DO PISO DE PRAÇA"),
        ("LIMPEZA DE COIFA", "LIMPEZA DE COIFA"),
        ("LIMPEZA DE COIFA DE COZINHA", "LIMPEZA DE COIFA DE COZINHA"),
        ("LIMPEZA DE COMPARTIMENTOS VOID E COFFERDANS", "LIMPEZA DE COMPARTIMENTOS VOID E COFFERDANS"),
        ("LIMPEZA DE DUTOS ", "LIMPEZA DE DUTOS "),
        ("LIMPEZA DE DUTOS DA LAVANDERIA", "LIMPEZA DE DUTOS DA LAVANDERIA"),
        ("LIMPEZA DE DUTOS DE AR CONDICIONADO", "LIMPEZA DE DUTOS DE AR CONDICIONADO"),
        ("LIMPEZA DE EXAUSTOR DE COZINHA", "LIMPEZA DE EXAUSTOR DE COZINHA"),
        ("LIMPEZA DE LAVANDERIA", "LIMPEZA DE LAVANDERIA"),
        ("LIMPEZA DE SILOS", "LIMPEZA DE SILOS"),
        ("LIMPEZA DE TANQUE DE ÁGUA", "LIMPEZA DE TANQUE DE ÁGUA"),
        ("LIMPEZA DE TANQUE DE BILGE", "LIMPEZA DE TANQUE DE BILGE"),
        ("LIMPEZA DE TANQUE DE CARGA", "LIMPEZA DE TANQUE DE CARGA"),
        ("LIMPEZA DE TANQUE DE DIESEL", "LIMPEZA DE TANQUE DE DIESEL"),
        ("LIMPEZA DE TANQUE DE DRENO", "LIMPEZA DE TANQUE DE DRENO"),
        ("LIMPEZA DE TANQUE DE LAMA", "LIMPEZA DE TANQUE DE LAMA"),
        ("LIMPEZA DE TANQUE DE LASTRO", "LIMPEZA DE TANQUE DE LASTRO"),
        ("LIMPEZA DE TANQUE DE MGO", "LIMPEZA DE TANQUE DE MGO"),
        ("LIMPEZA DE TANQUE DE ÓLEO", "LIMPEZA DE TANQUE DE ÓLEO"),
        ("LIMPEZA DE TANQUE DE RETENÇÃO DE DRENAGEM", "LIMPEZA DE TANQUE DE RETENÇÃO DE DRENAGEM"),
        ("LIMPEZA DE TANQUE DE SETTLING (ÓLEO)", "LIMPEZA DE TANQUE DE SETTLING (ÓLEO)"),
        ("LIMPEZA DE TANQUE DE SEWAGE/ESGOTO", "LIMPEZA DE TANQUE DE SEWAGE/ESGOTO"),
        ("LIMPEZA DE TANQUE DE SLOP", "LIMPEZA DE TANQUE DE SLOP"),
        ("LIMPEZA DE TANQUE RECOVERY", "LIMPEZA DE TANQUE RECOVERY"),
        ("LIMPEZA DE TANQUES DE ÁGUA POTÁVEL", "LIMPEZA DE TANQUES DE ÁGUA POTÁVEL"),
        ("LIMPEZA DE TANQUES DE ÓLEO DIESEL", "LIMPEZA DE TANQUES DE ÓLEO DIESEL"),
        ("LIMPEZA DE TANQUES DE SLUDGE", "LIMPEZA DE TANQUES DE SLUDGE"),
        ("LIMPEZA DE TANQUES EM GERAL", "LIMPEZA DE TANQUES EM GERAL"),
        ("LIMPEZA DE VASO", "LIMPEZA DE VASO"),
        ("LIMPEZA DE VASOS", "LIMPEZA DE VASOS"),
        ("LIMPEZA E DESCONTAMINAÇÃO DE CARRETA", "LIMPEZA E DESCONTAMINAÇÃO DE CARRETA"),
        ("LIMPEZA GERAL NA EMBARCAÇÃO", "LIMPEZA GERAL NA EMBARCAÇÃO"),
        ("LIMPEZA, TRATAMENTO E PINTURA", "LIMPEZA, TRATAMENTO E PINTURA"),
        ("LOCAÇÃO DE EQUIPAMENTOS", "LOCAÇÃO DE EQUIPAMENTOS"),
        ("MEDIÇÃO DE ESPESSURA", "MEDIÇÃO DE ESPESSURA"),
        ("MOBILIZAÇÃO DE EQUIPAMENTOS", "MOBILIZAÇÃO DE EQUIPAMENTOS"),
        ("MOBILIZAÇÃO DE PESSOAS", "MOBILIZAÇÃO DE PESSOAS"),
        ("MOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS", "MOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS"),
        ("MOBILIZAÇÃO/DESMOBILIZAÇÃO DE CARRETA TANQUE", "MOBILIZAÇÃO/DESMOBILIZAÇÃO DE CARRETA TANQUE"),
        ("PINTURA", "PINTURA"),
        ("RADIOPROTEÇÃO NORM", "RADIOPROTEÇÃO NORM"),
        ("RE-LIMPEZA DE TANQUES APÓS FLUSHING", "RE-LIMPEZA DE TANQUES APÓS FLUSHING"),
        ("RENOVAÇÃO DO PMOC", "RENOVAÇÃO DO PMOC"),
        ("SEGREGAÇÃO, SINALIZAÇÃO E ISOLAMENTO DE REJEITOS", "SEGREGAÇÃO, SINALIZAÇÃO E ISOLAMENTO DE REJEITOS"),
        ("SERVIÇO DE IRATA", "SERVIÇO DE IRATA"),
        ("SHUT DOWN", "SHUT DOWN"),
        ("SURVEY PARA AVALIAÇÃO DE ATIVIDADE", "SURVEY PARA AVALIAÇÃO DE ATIVIDADE"),
        ("TAXA DIARIA DE AUXILIAR A DISPOSIÇÃO", "TAXA DIARIA DE AUXILIAR A DISPOSIÇÃO"),
        ("TAXA DIARIA DE SUPERVISOR/OPERADOR A DISPOSIÇÃO", "TAXA DIARIA DE SUPERVISOR/OPERADOR A DISPOSIÇÃO"),
        ("TAXA MENSAL DE EQUIPE ONSHORE", "TAXA MENSAL DE EQUIPE ONSHORE"),
        ("VIGIA", "VIGIA"),
    ]

    TIPO_OP_CHOICES = [
        ('Onshore', 'Onshore'),
        ('Offshore', 'Offshore'),
        ('Spot Onshore', 'Spot Onshore'),
        ('Spot Offshore', 'Spot Offshore'),
    ]

    STATUS_CHOICES = [
        ('Programada', 'Programada'),
        ('Em Andamento', 'Em Andamento'),
        ('Paralizada', 'Paralizada'),
        ('Finalizada', 'Finalizada'),
    ]

    METODO_CHOICES = [
        ('Manual', 'Manual'),
        ('Mecanizada', 'Mecanizada'),
        ('Robotizada', 'Robotizada'),
        ('Roto rooter', 'Roto rooter'),
        ('Demais', 'Demais'),
    ]
    CLIENTE_CHOICES = [
         ('3R', '3R'),
        ('A M DE SOUZA GOMES', 'A M DE SOUZA GOMES'),
        ('ACELEN', 'ACELEN'),
        ('AEROPREST', 'AEROPREST'),
        ('AGUAS DO RIO', 'AGUAS DO RIO'),
        ('AK OPERACOES', 'AK OPERACOES'),
        ('AKDENIZ', 'AKDENIZ'),
        ('SBM DO BRASIL', 'SBM DO BRASIL'),
        ('ALLONDA', 'ALLONDA'),
        ('ALPEK POLYESTER', 'ALPEK POLYESTER'),
        ('ALTARQ', 'ALTARQ'),
        ('ALTERA', 'ALTERA'),
        ('AMBIPAR RESPONSE', 'AMBIPAR RESPONSE'),
        ('ARACAJU', 'ARACAJU'),
        ('ARCELORMITTAL', 'ARCELORMITTAL'),
        ('ARLANXEO', 'ARLANXEO'),
        ('ASGAARD', 'ASGAARD'),
        ('ASSO MARITIMA', 'ASSO MARITIMA'),
        ('ASSOCIACAO DAS TESTEMUNHAS CRISTAS DE JEOVA', 'ASSOCIACAO DAS TESTEMUNHAS CRISTAS DE JEOVA'),
        ('BELOV', 'BELOV'),
        ('ADITYA BIRLA GROUP', 'ADITYA BIRLA GROUP'),
        ('BKF ENGENHARIA', 'BKF ENGENHARIA'),
        ('BLUE MARINE TELECOM', 'BLUE MARINE TELECOM'),
        ('BRAVANTE', 'BRAVANTE'),
        ('BUNKER ONE', 'BUNKER ONE'),
        ('BW LNG SERVICOS', 'BW LNG SERVICOS'),
        ('CARGILL', 'CARGILL'),
        ('CASA GRANADO', 'CASA GRANADO'),
        ('CATTALINI TERMINAIS MARITIMOS', 'CATTALINI TERMINAIS MARITIMOS'),
        ('CBO', 'CBO'),
        ('CHANTIERS DE LATLANTIQUE', 'CHANTIERS DE LATLANTIQUE'),
        ('COMERCIAL PAULOS', 'COMERCIAL PAULOS'),
        ('COMPANHIA DE DESENVOLVIMENTO DA PESCA', 'COMPANHIA DE DESENVOLVIMENTO DA PESCA'),
        ('COMGAS', 'COMGAS'),
        ('COMTEX', 'COMTEX'),
        ('CONCREMAT', 'CONCREMAT'),
        ('CONSTRUTORA CANOPUS', 'CONSTRUTORA CANOPUS'),
        ('CRISTAL CONSTRUCOES', 'CRISTAL CONSTRUCOES'),
        ('DM CONSULTORIA', 'DM CONSULTORIA'),
        ('DOF SUBSEA', 'DOF SUBSEA'),
        ('DOFCON', 'DOFCON'),
        ('DOLABELLA', 'DOLABELLA'),
        ('ECOVIX', 'ECOVIX'),
        ('ELETRISERVICE', 'ELETRISERVICE'),
        ('EMBRAER', 'EMBRAER'),
        ('AMBIPAR', 'AMBIPAR'),
        ('ELCANO', 'ELCANO'),
        ('EMPRESA DE TRANSPORTES FLORES', 'EMPRESA DE TRANSPORTES FLORES'),
        ('ENGEATEC', 'ENGEATEC'),
        ('ENGEMAR', 'ENGEMAR'),
        ('ENORSUL', 'ENORSUL'),
        ('EQUINOR', 'EQUINOR'),
        ('ESTALEIRO MAUA', 'ESTALEIRO MAUA'),
        ('ESTRELA DA BORRACHA', 'ESTRELA DA BORRACHA'),
        ('EXPRESSO REAL RIO', 'EXPRESSO REAL RIO'),
        ('FAZENDAO', 'FAZENDAO'),
        ('FUGRO BRASIL', 'FUGRO BRASIL'),
        ('FUNDACAO EDUCACIONAL DE PATOS', 'FUNDACAO EDUCACIONAL DE PATOS'),
        ('GC OPERACOES MARITIMAS', 'GC OPERACOES MARITIMAS'),
        ('GEOGAS', 'GEOGAS'),
        ('GRAN SERVICES', 'GRAN SERVICES'),
        ('GRANENERGIA', 'GRANENERGIA'),
        ('GRANOL', 'GRANOL'),
        ('HALLIBURTON', 'HALLIBURTON'),
        ('HELIX DO BRASIL', 'HELIX DO BRASIL'),
        ('HNK BR', 'HNK BR'),
        ('HORNBECK', 'HORNBECK'),
        ('HPA BRASIL', 'HPA BRASIL'),
        ('IGOR VIDAL MEIRELLES', 'IGOR VIDAL MEIRELLES'),
        ('IGREJA PLENA', 'IGREJA PLENA'),
        ('IGUA', 'IGUA'),
        ('IKM', 'IKM'),
        ('INOVE ANDAIMES', 'INOVE ANDAIMES'),
        ('ITAGUAI', 'ITAGUAI'),
        ('ITUIUTABA BIOENERGIA', 'ITUIUTABA BIOENERGIA'),
        ('J Z ENGENHARIA', 'J Z ENGENHARIA'),
        ('J&D CONSULTORIA', 'J&D CONSULTORIA'),
        ('JOAO BATISTA DA SILVA', 'JOAO BATISTA DA SILVA'),
        ('K S SERVICOS', 'K S SERVICOS'),
        ('KARPOWERSHIP', 'KARPOWERSHIP'),te 
        ('KLABIN', 'KLABIN'),
        ('KM IMPERMEABILIZANTES', 'KM IMPERMEABILIZANTES'),
        ('L OLIVEIRA', 'L OLIVEIRA'),
        ('LARGO VANADIO', 'LARGO VANADIO'),
        ('LD CELULOSE', 'LD CELULOSE'),
        ('LILIANE MARINGA', 'LILIANE MARINGA'),
        ('LOCAR GUINDASTES', 'LOCAR GUINDASTES'),
        ('LOG-IN', 'LOG-IN'),
        ('LX COMERCIO', 'LX COMERCIO'),
        ('MANTEP', 'MANTEP'),
        ('OCEANPACT', 'OCEANPACT'),
        ('MARINGA', 'MARINGA'),
        ('MERO 2 OPERACOES MARITIMAS', 'MERO 2 OPERACOES MARITIMAS'),
        ('MOC SERVICOS', 'MOC SERVICOS'),
        ('MODEC', 'MODEC'),
        ('NEOLUBES', 'NEOLUBES'),
        ('NEX DEDETIZADORA', 'NEX DEDETIZADORA'),
        ('NOURYON', 'NOURYON'),
        ('NPE SERVICE', 'NPE SERVICE'),
        ('OCEANPACT', 'OCEANPACT'),
        ('OCYAN', 'OCYAN'),
        ('OOGTK', 'OOGTK'),
        ('OPERSAN', 'OPERSAN'),
        ('PAES', 'PAES'),
        ('PARECIS', 'PARECIS'),
        ('PERBRAS', 'PERBRAS'),
        ('PERENCO', 'PERENCO'),
        ('PETROBRÁS', 'PETROBRÁS'),
        ('POSEIDON', 'POSEIDON'),
        ('POSIDONIA SHIPPING', 'POSIDONIA SHIPPING'),
        ('ORLANDIA', 'ORLANDIA'),
        ('PROSAFE', 'PROSAFE'),
        ('QGP QUIMICA', 'QGP QUIMICA'),
        ('QUALITECH', 'QUALITECH'),
        ('RESERMAX', 'RESERMAX'),
        ('RESILOG', 'RESILOG'),
        ('RF SOLUCOES ELETRICAS', 'RF SOLUCOES ELETRICAS'),
        ('RG ESTALEIRO', 'RG ESTALEIRO'),
        ('RIO PARDO', 'RIO PARDO'),
        ('RIOSANTOS', 'RIOSANTOS'),
        ('RNF', 'RNF'),
        ('S.R.T TAVARES', 'S.R.T TAVARES'),
        ('SANTA PAULINA', 'SANTA PAULINA'),
        ('SCHLUMBERGER', 'SCHLUMBERGER'),
        ('SD ENGENHARIA', 'SD ENGENHARIA'),
        ('SEADRILL', 'SEADRILL'),
        ('SEANUTRI CONSULTORIA', 'SEANUTRI CONSULTORIA'),
        ('SELLOS ENGENHARIA', 'SELLOS ENGENHARIA'),
        ('SERVICE NAVE', 'SERVICE NAVE'),
        ('CONSTELLATION', 'CONSTELLATION'),
        ('SIEM OFFSHORE', 'SIEM OFFSHORE'),
        ('SISTAC', 'SISTAC'),
        ('STARNAV', 'STARNAV'),
        ('SUPPLY OFFSHORE', 'SUPPLY OFFSHORE'),
        ('SUPREMAX NUTRIÇÃO', 'SUPREMAX NUTRIÇÃO'),
        ('SVITZER BRASIL', 'SVITZER BRASIL'),
        ('TECHDOF', 'TECHDOF'),
        ('TECHNIP', 'TECHNIP'),
        ('TECHOCEAN', 'TECHOCEAN'),
        ('TERNIUM', 'TERNIUM'),
        ('THG SERVIÇOS', 'THG SERVIÇOS'),
        ('THYSSENKRUPP', 'THYSSENKRUPP'),
        ('TRANSOCEAN', 'TRANSOCEAN'),
        ('TRIDENT', 'TRIDENT'),
        ('TRIMOL', 'TRIMOL'),
        ('TRIUNFO', 'TRIUNFO'),
        ('UNIKA', 'UNIKA'),
        ('USINA SAO JOSE DA ESTIVA', 'USINA SAO JOSE DA ESTIVA'),
        ('V. SHIPS BRASIL', 'V. SHIPS BRASIL'),
        ('VALE', 'VALE'),
        ('VERTICAL SERVICOS', 'VERTICAL SERVICOS'),
        ('VIBRA ENERGIA', 'VIBRA ENERGIA'),
        ('VITORIA AMBIENTAL ENGENHARIA', 'VITORIA AMBIENTAL ENGENHARIA'),
        ('WILSON SONS', 'WILSON SONS'),
        ('YINSON BOUVARDIA', 'YINSON BOUVARDIA'),
        ('NOVA OFFSHORE', 'NOVA OFFSHORE'),
        ('NORSUL', 'NORSUL'),
        ('SUPPLY LOG OIL & GAS', 'SUPPLY LOG OIL & GAS'),
        ('ALIANCA S/A', 'ALIANCA S/A'),
        ('SEAGEMS OFFSHORE', 'SEAGEMS OFFSHORE'),
        ('ENAUTA ENERGIA', 'ENAUTA ENERGIA'),
        ('GLP GAS DISTRIBUIDORA DE GAS LTDA', 'GLP GAS DISTRIBUIDORA DE GAS LTDA'),
        ('INPASA AGROINDUSTRIAL', 'INPASA AGROINDUSTRIAL'),
        ('HYDRATIGHT', 'HYDRATIGHT'),
        ('BRAM OFFSHORE', 'BRAM OFFSHORE'),
        ('PEDRA AGROINDUSTRIAL', 'PEDRA AGROINDUSTRIAL'),
        ('LIMPIND ASSEIO', 'LIMPIND ASSEIO'),
        ('CKBR BEBIDAS', 'CKBR BEBIDAS'),
        ('LOUIS DREYFUS', 'LOUIS DREYFUS'),
        ('VOTORANTIM CIMENTOS', 'VOTORANTIM CIMENTOS'),
        ('TORRES ENGENHARIA', 'TORRES ENGENHARIA'),
        ('METALNAV', 'METALNAV'),
        ('TOP SERVE INTERNATIONAL', 'TOP SERVE INTERNATIONAL'),
        ('SEVEN CLEAN SERVICOS MARITIMOS', 'SEVEN CLEAN SERVICOS MARITIMOS'),
        ('AF. SOLUCOES AMBIENTAIS', 'AF. SOLUCOES AMBIENTAIS'),
        ('OCEANEERING', 'OCEANEERING'),
        ('TSL ENGENHARIA', 'TSL ENGENHARIA'),
        ('DEDETIZADORA ITABORAI', 'DEDETIZADORA ITABORAI'),
        ('HDM REPRESENTANTES COMERCIAIS', 'HDM REPRESENTANTES COMERCIAIS'),
        ('USINANDO INDUSTRIA', 'USINANDO INDUSTRIA'),
        ('MULTIPLA EM CONSTRUCAO', 'MULTIPLA EM CONSTRUCAO'),
        ('GEOLOGUS', 'GEOLOGUS'),
        ('SOLVE CLEANING', 'SOLVE CLEANING'),
        ('SEA1 OFFSHORE', 'SEA1 OFFSHORE'),
        ('CBA', 'CBA'),
        ('SAMARCO', 'SAMARCO'),
        ('HEINEKEN', 'HEINEKEN'),
        ('PRIO', 'PRIO'),
        ('PETROGOTAS', 'PETROGOTAS'),
        ('DEDEFONE', 'DEDEFONE'),
    ]
    
    STATUS_COMERCIAL_CHOICES = [
        ('Faturado', 'Faturado'),
        ('Em aberto', 'Em aberto'),
        ('Cancelado', 'Cancelado'),
    ]

    UNIDADE_CHOICES = [
        ("MV-15", "MV-15"),
        ("MV-23", "MV-23"),
        ("MV29", "MV29"),
        ("MV27", "MV27"),
        ("MV-30", "MV-30"),
        ("MV-22", "MV-22"),
        ("MV-24", "MV-24"),
        ("MV-26", "MV-26"),
        ("MV-29", "MV-29"),
        ("MV-33", "MV-33"),
        ("P-76", "P-76"),
        ("P-74", "P-74"),
        ("P-77", "P-77"),
        ("CDI", "CDI"),
        ("CDA", "CDA"),
        ("FPSO SEPETIBA", "FPSO SEPETIBA"),
        ("CDM", "CDM"),
        ("FPSO ALMIRANTE TAMANDARÉ", "FPSO ALMIRANTE TAMANDARÉ"),
        ("FPSO PIONEIRO DE LIBRA", "FPSO PIONEIRO DE LIBRA"),
        ("CDS -CIDADE DE SAQUAREMA", "CDS -CIDADE DE SAQUAREMA"),
        ("FPSO CIDADE ITAJAÍ", "FPSO CIDADE ITAJAÍ"),
        ("Peregrino A", "Peregrino A"),
        ("FPSO PEREGRINO", "FPSO PEREGRINO"),
        ("HAP", "HAP"),
        ("WEST SATURN", "WEST SATURN"),
        ("WEST JUPITER", "WEST JUPITER"),
        ("CVIT", "CVIT"),
        ("SH2", "SH2"),
        ("PBS 10000", "PBS 10000"),
        ("SH1", "SH1"),
        ("ANNA NERY", "ANNA NERY"),
        ("NORBE VIII", "NORBE VIII"),
        ("WEST CARINA", "WEST CARINA"),
        ("3R-3", "3R-3"),
        ("WEST TELLUS", "WEST TELLUS"),
        ("WEST AURIGA", "WEST AURIGA"),
        ("CORCOVADO", "CORCOVADO"),
        ("PPM1", "PPM1"),
        ("DS-15", "DS-15"),
        ("CDP", "CDP"),
        ("P-75", "P-75"),
        ("LAGUNA STAR", "LAGUNA STAR"),
        ("Q7000", "Q7000"),
    ]

    SERVICO_TAG_MAP = {
        "ACOMPANHAMENTO DE FLUSHING OU TRANSFERÊNCIA": "ACO",
        "ARMAZENAMENTO TEMPORÁRIO": "ART",
        "CARRETA DE ARMAZENAMENTO TEMPORÁRIO": "CAT",
        "CERTIFICAÇÃO GAS FIRE": "GFI",
        "CERTIFICAÇÃO GAS FREE": "GFE",
        "COLETA E ANÁLISE DA ÁGUA": "CAG",
        "COLETA E ANÁLISE DO AR": "CAA",
        "DESCARTE DE RESIDUOS": "DER",
        "DESCOMISSIONAMENTO": "DES",
        "DESCONTAMINAÇÃO PROFUNDA NA EMBARCAÇÃO": "DPE",
        "DESMOBILIZAÇÃO DE EQUIPAMENTOS": "DEQ",
        "DESMOBILIZAÇÃO DE PESSOAS": "DEE",
        "DESMOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS": "EEQ",
        "DESOBSTRUÇÃO": "DBT",
        "DESOBSTRUÇÃO DA LINHA DE DRENAGEM ABERTA": "DLD",
        "DIÁRIA DA EQUIPE DE LIMPEZA DE TANQUES": "DEL",
        "DIÁRIA DE AJUDANTE OPERACIONAL": "DAO",
        "DIÁRIA DE CONSUMÍVEIS PARA LIMPEZA": "DCO",
        "DIÁRIA DE CONSUMÍVEIS PARA PINTURA": "CPP",
        "DIÁRIA DE RESGATISTA": "DRE",
        "DIÁRIA DE SUPERVISOR": "DPR",
        "DIÁRIA DO TÉCNICO DE SEGURANÇA DO TRABALHO": "TST",
        "ELABORAÇÃO DO PMOC": "EPM",
        "EMISSÃO DE FREE FOR FIRE": "FFF",
        "ENSACAMENTO E REMOÇÃO": "ENR",
        "EQUIPAMENTOS EM STAND BY": "STB",
        "EQUIPE EM STAND BY": "EST",
        "ESGOTAMENTO DE RESÍDUO": "ERE",
        "FORNECIMENTO DE ALMOXARIFE": "FAL",
        "FORNECIMENTO DE AUXILIAR OFFSHORE": "FAU",
        "FORNECIMENTO DE CAMINHÃO VÁCUO": "FCV",
        "FORNECIMENTO DE CARRETA TANQUE": "FCT",
        "FORNECIMENTO DE ELETRICISTA": "FEL",
        "FORNECIMENTO DE ENGENHEIRO QUÍMICO": "ENQ",
        "FORNECIMENTO DE EQUIPAMENTOS E CONSUMÍVEIS": "EQC",
        "FORNECIMENTO DE EQUIPE DE ALPINISTA INDUSTRIAL": "ALP",
        "FORNECIMENTO DE EQUIPE DE RESGATE": "ERS",
        "FORNECIMENTO DE IRATA N1 OU N2": "FIR",
        "FORNECIMENTO DE IRATA N3": "FIN",
        "FORNECIMENTO DE MÃO DE OBRA OPERACIONAL": "MAO",
        "FORNECIMENTO DE MATERIAIS": "MAT",
        "FORNECIMENTO DE MECÂNICO": "MEC",
        "FORNECIMENTO DE QUÍMICOS": "QUI",
        "FORNECIMENTO DE TÉCNICO OFFSHORE": "TEC",
        "HORA EXTRA CARRETA TANQUE (APÓS 4H DE FRANQUIA)": "EXT",
        "HOTEL, ALIMENTAÇÃO E TRANSFER POR PAX": "HAT",
        "INSPEÇÃO DE TANQUE": "INS",
        "INSPEÇÃO POR BOROSCÓPIO": "IBO",
        "INVENTÁRIO, LISTA DE VERIFICAÇÃO E PLANEJAMENTO DOS MATERIAIS A BORDO.": "INV",
        "LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR + LAVANDERIA)": "DCL",
        "LIMPEZA (DUTOS + COIFA + COLETA E ANÁLISE DE AR)": "DCA",
        "LIMPEZA (DUTOS + COIFA)": "LDC",
        "LIMPEZA DA CASA DE BOMBAS": "LCB",
        "LIMPEZA DE AGUAS CINZAS": "LAC",
        "LIMPEZA DE AGUAS NEGRAS": "LAN",
        "LIMPEZA DE ÁREA DO PISO DE PRAÇA": "APP",
        "LIMPEZA DE COIFA": "LCF",
        "LIMPEZA DE COIFA DE COZINHA": "LCC",
        "LIMPEZA DE COMPARTIMENTOS VOID E COFFERDANS": "VOI",
        "LIMPEZA DE DUTOS": "LDD",
        "LIMPEZA DE DUTOS DA LAVANDERIA": "DUT",
        "LIMPEZA DE DUTOS DE AR CONDICIONADO": "ARC",
        "LIMPEZA DE EXAUSTOR DE COZINHA": "EXC",
        "LIMPEZA DE LAVANDERIA": "LDL",
        "LIMPEZA DE SILOS": "SIL",
        "LIMPEZA DE TANQUE DE ÁGUA": "LTA",
        "LIMPEZA DE TANQUE DE BILGE": "LTB",
        "LIMPEZA DE TANQUE DE CARGA": "LTC",
        "LIMPEZA DE TANQUE DE DIESEL": "LTD",
        "LIMPEZA DE TANQUE DE DRENO": "LDR",
        "LIMPEZA DE TANQUE DE LAMA": "LTL",
        "LIMPEZA DE TANQUE DE LASTRO": "TLA",
        "LIMPEZA DE TANQUE DE MGO": "MGO",
        "LIMPEZA DE TANQUE DE ÓLEO": "LTO",
        "LIMPEZA DE TANQUE DE RETENÇÃO DE DRENAGEM": "LRD",
        "LIMPEZA DE TANQUE DE SETTLING (ÓLEO)": "LTS",
        "LIMPEZA DE TANQUE DE SEWAGE/ESGOTO": "TSE",
        "LIMPEZA DE TANQUE DE SLOP": "LSL",
        "LIMPEZA DE TANQUE RECOVERY": "LTR",
        "LIMPEZA DE TANQUES DE ÁGUA POTÁVEL": "AGP",
        "LIMPEZA DE TANQUES DE ÓLEO DIESEL": "LOD",
        "LIMPEZA DE TANQUES DE SLUDGE": "SLU",
        "LIMPEZA DE TANQUES EM GERAL": "LTG",
        "LIMPEZA DE VASO": "LDV",
        "LIMPEZA DE VASOS": "VAS",
        "LIMPEZA E DESCONTAMINAÇÃO DE CARRETA": "DEC",
        "LIMPEZA GERAL NA EMBARCAÇÃO": "LGE",
        "LIMPEZA, TRATAMENTO E PINTURA": "LTP",
        "LOCAÇÃO DE EQUIPAMENTOS": "LOE",
        "MEDIÇÃO DE ESPESSURA": "MES",
        "MOBILIZAÇÃO DE EQUIPAMENTOS": "MOE",
        "MOBILIZAÇÃO DE PESSOAS": "MOP",
        "MOBILIZAÇÃO DE PESSOAS E EQUIPAMENTOS": "MPE",
        "MOBILIZAÇÃO/DESMOBILIZAÇÃO DE CARRETA TANQUE": "MDS",
        "PINTURA": "PIN",
        "RADIOPROTEÇÃO NORM": "RAD",
        "RE-LIMPEZA DE TANQUES APÓS FLUSHING": "REL",
        "RENOVAÇÃO DO PMOC": "RPM",
        "SEGREGAÇÃO, SINALIZAÇÃO E ISOLAMENTO DE REJEITOS": "SSI",
        "SERVIÇO DE IRATA": "SIR",
        "SHUT DOWN": "SHD",
        "SURVEY PARA AVALIAÇÃO DE ATIVIDADE": "SUR",
        "TAXA DIARIA DE AUXILIAR A DISPOSIÇÃO": "TDA",
        "TAXA DIARIA DE SUPERVISOR/OPERADOR A DISPOSIÇÃO": "TDS",
        "TAXA MENSAL DE EQUIPE ONSHORE": "TEO",
        "VIGIA": "VIG"
    }

    tag = models.CharField(max_length=3, choices=TAG_CHOICES)
    numero_os = models.IntegerField()
    codigo_os = models.CharField(max_length=20)
    especificacao = models.CharField(max_length=255, null=True, blank=True)
    data_inicio = models.DateField()
    data_fim = models.DateField(null=True, blank=True)
    dias_de_operacao = models.IntegerField()
    servico = models.CharField(max_length=100, choices=SERVICO_CHOICES)
    metodo = models.CharField(max_length=20, choices=METODO_CHOICES)
    observacao = models.TextField(blank=True)
    pob = models.IntegerField()
    tanque = models.CharField(max_length=50, blank=True)
    volume_tanque = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    cliente = models.CharField(max_length=100, choices=CLIENTE_CHOICES)
    unidade = models.CharField(max_length=50, choices=UNIDADE_CHOICES)
    tipo_operacao = models.CharField(max_length=50, choices=TIPO_OP_CHOICES)
    solicitante = models.CharField(max_length=50)
    coordenador = models.CharField(max_length=50)
    supervisor = models.CharField(max_length=50)
    status_operacao = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Programada')
    # Coluna para colocar um botão que leva para o link do RDO
    link_rdo = models.URLField(blank=True, null=True)
    # Coluna para colocar um botão para abrir uma janela com detalhes da operação
    detalhes = models.TextField(blank=True, null=True)
    status_comercial = models.CharField(max_length=20, choices=STATUS_COMERCIAL_CHOICES, default='Em aberto')
    
    # Calculo de dias de operação
    def save(self, *args, **kwargs):
        if self.data_fim and self.data_inicio:
            self.dias_de_operacao = (self.data_fim - self.data_inicio).days
        else:
            self.dias_de_operacao = 0
        super().save(*args, **kwargs)


    def __str__(self):
        return self.codigo_os
