"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pwb^w4t%9fplrljnh7h*4v%p+yfg^po)mf@2vtf_j7f@)(!lmm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Em desenvolvimento, liste explicitamente os hosts permitidos (recomendado)
ALLOWED_HOSTS = [
    "synchro.ambipar.vps-kinghost.net",
    "177.153.69.133",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'GO.apps.GoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <- Ajuste necessário aqui
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "GO/static"]
STATIC_ROOT = "/var/www/html/GESTAO_OPERACIONAL/static/"

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/html/GESTAO_OPERACIONAL/fotos_rdo/'

# Email backend: permite override via variável de ambiente DJANGO_EMAIL_BACKEND.
# Em desenvolvimento o `setup/settings_dev.py` já define:
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')


# Injetar middleware restritivo para contas do grupo 'Supervisor' em dev
try:
    MIDDLEWARE = list(MIDDLEWARE)
    mw = 'GO.middleware.supervisor_middleware.SupervisorForceRdoMiddleware'
    if mw not in MIDDLEWARE:
        # inserir após AuthenticationMiddleware para que user esteja disponível
        try:
            idx = MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware')
            MIDDLEWARE.insert(idx + 1, mw)
        except ValueError:
            MIDDLEWARE.append(mw)
except Exception:
    # se algo falhar, não impedir o startup
    pass

# Injetar context processor para detectar mobile em desenvolvimento (opcional)
try:
    cp = 'GO.context_processors.mobile_detector'
    if 'TEMPLATES' in globals() and isinstance(TEMPLATES, (list, tuple)) and len(TEMPLATES) > 0:
        try:
            opts = TEMPLATES[0].setdefault('OPTIONS', {})
            cps = opts.setdefault('context_processors', [])
            if cp not in cps:
                cps.append(cp)
        except Exception:
            pass
except Exception:
    pass


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Autenticação por e-mail
AUTHENTICATION_BACKENDS = [
    'GO.email_backend.EmailBackend',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Temporary logging to capture unhandled exceptions (used for emergency debugging).
# This will write ERROR-level logs (including tracebacks) to /var/log/django_errors.log
# and also to stderr so they appear in gunicorn stdout/stderr. Remove after issue is fixed.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': '/var/log/django_errors.log',
            'formatter': 'verbose',
            'level': 'ERROR',
            'mode': 'a',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

