# Generated by Django 5.2.5 on 2025-08-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('LTA', 'LIMPEZA DE TANQUE DE ÁGUA'), ('SIR', 'SERVIÇO DE IRATA'), ('LTL', 'LIMPEZA DE TANQUE DE LAMA'), ('LDC', 'LIMPEZA DE DUTO E COIFA'), ('LDV', 'LIMPEZA DE VASO'), ('LMC', 'LIMPEZA MECANIZADA'), ('LTO', 'LIMPEZA TANQUE DE ÓLEO'), ('LTC', 'LIMPEZA TANQUE DE CARGA'), ('LRB', 'LIMPEZA ROBOTIZADA'), ('LDA', 'LIMPEZA DE DUTOS DE AR CONDICIONADO'), ('LDE', 'LIMPEZA DE DUTOS DE EXAUSTÃO'), ('LCC', 'LIMPEZA DE COIFA DA COZINHA'), ('CAA', 'COLETA E ANÁLISE DO AR AMBIENTE')], max_length=3)),
                ('numero_os', models.IntegerField(unique=True)),
                ('codigo_os', models.CharField(max_length=20, unique=True)),
                ('descriçao', models.TextField()),
            ],
        ),
    ]
