# Generated by Django 5.2.5 on 2025-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('LTA', 'LTA'), ('SIR', 'SIR'), ('LTL', 'LTL'), ('LDC', 'LDC'), ('LDV', 'LDV'), ('LMC', 'LMC'), ('LTO', 'LTO'), ('LTC', 'LTC'), ('LRB', 'LRB'), ('LDA', 'LDA'), ('LDE', 'LDE'), ('LCC', 'LCC'), ('CAA', 'CAA')], max_length=3)),
                ('numero_os', models.IntegerField(unique=True)),
                ('codigo_os', models.CharField(max_length=20, unique=True)),
                ('especificacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('dias_de_operacao', models.IntegerField()),
                ('servico', models.CharField(choices=[('LIMPEZA DE TANQUE DE ÁGUA', 'LIMPEZA DE TANQUE DE ÁGUA'), ('SERVIÇO DE IRATA', 'SERVIÇO DE IRATA'), ('LIMPEZA DE TANQUE DE LAMA', 'LIMPEZA DE TANQUE DE LAMA'), ('LIMPEZA DE DUTO E COIFA', 'LIMPEZA DE DUTO E COIFA'), ('LIMPEZA DE VASO', 'LIMPEZA DE VASO'), ('LIMPEZA MECANIZADA', ' LIMPEZA MECANIZADA'), ('LIMPEZA TANQUE DE ÓLEO', 'LIMPEZA TANQUE DE ÓLEO'), ('LIMPEZA TANQUE DE CARGA', 'LIMPEZA TANQUE DE CARGA'), ('LIMPEZA ROBOTIZADA', 'LIMPEZA ROBOTIZADA'), ('LIMPEZA DE DUTOS DE AR CONDICIONADO', 'LIMPEZA DE DUTOS DE AR CONDICIONADO'), ('LIMPEZA DE DUTOS DE EXAUSTÃO', 'LIMPEZA DE DUTOS DE EXAUSTÃO'), ('LIMPEZA DE COIFA DA COZINHA', 'LIMPEZA DE COIFA DA COZINHA'), ('COLETA E ANÁLISE DO AR AMBIENTE', 'COLETA E ANÁLISE DO AR AMBIENTE')], max_length=50)),
                ('metodo', models.CharField(choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('Demais', 'Demais')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('pob', models.IntegerField()),
                ('tanque', models.CharField(blank=True, max_length=50)),
                ('volume_tanque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.CharField(max_length=50)),
                ('unidade', models.CharField(max_length=50)),
                ('tipo_operacao', models.CharField(choices=[('Onshore', 'Onshore'), ('Offshore', 'Offshore'), ('Spot Onshore', 'Spot Onshore'), ('Spot Offshore', 'Spot Offshore')], max_length=50)),
                ('solicitante', models.CharField(max_length=50)),
                ('coordenador', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('status_operacao', models.CharField(choices=[('Programada', 'Programada'), ('Em Andamento', 'Em Andamento'), ('Paralizada', 'Paralizada'), ('Finalizada', 'Finalizada')], default='Programada', max_length=50)),
                ('link_rdo', models.URLField(blank=True, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
