# Generated by Django 4.2.24 on 2025-10-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='pessoas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rdos', to='GO.pessoa'),
        ),
    ]
