# Generated by Django 5.2.5 on 2025-08-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0002_alter_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='volume_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
