# Generated by Django 4.2.24 on 2025-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0002_alter_rdo_pessoas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curva_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza_mecanizada', models.IntegerField()),
                ('ensacamento', models.IntegerField()),
                ('içamento', models.IntegerField()),
                ('bombeio', models.IntegerField()),
                ('cambagem', models.IntegerField()),
                ('lavagem_fina', models.IntegerField()),
                ('avanco_total', models.IntegerField()),
            ],
        ),
    ]
