# Generated by Django 5.2.5 on 2025-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0003_alter_ordemservico_volume_tanque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.IntegerField(),
        ),
    ]
