# Generated by Django 4.2.24 on 2025-10-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0003_curva_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio_tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpeza_mecanizada_op', models.IntegerField(default=0)),
                ('ensacamento_op', models.IntegerField(default=0)),
                ('icamento_op', models.IntegerField(default=0)),
                ('bombeio_op', models.IntegerField(default=0)),
                ('cambagem_op', models.IntegerField(default=0)),
                ('lavagem_fina_op', models.IntegerField(default=0)),
                ('avanco_total_op', models.IntegerField(default=0)),
                ('total_hh_op_real', models.TimeField()),
                ('pob_op', models.IntegerField()),
                ('solidos_op_m3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('liquidos_op_m3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hh_disponivel_op', models.TimeField()),
                ('qtnd_sacos_op', models.IntegerField()),
                ('qtnd_tambores_op', models.IntegerField()),
                ('compartimentos_limpos_op', models.IntegerField()),
                ('gavetas_limpos_op', models.IntegerField()),
                ('ultimo_status', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Relatório Técnico',
                'verbose_name_plural': 'Relatórios Técnicos',
            },
        ),
        migrations.DeleteModel(
            name='Curva_s',
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['-data_inicio', 'numero_os'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='rdoatividade',
            options={'ordering': ['ordem'], 'verbose_name': 'Atividade de RDO', 'verbose_name_plural': 'Atividades de RDO'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='CO_ppm',
            new_name='co_ppm',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='H2S_ppm',
            new_name='h2s_ppm',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='LEL',
            new_name='lel',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='O2_percent',
            new_name='o2_percent',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='sent_limpeza',
            new_name='sentido_limpeza',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='serviço_rdo',
            new_name='servico_rdo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='codigo_os',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='controle_de_atividades',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='link_rdo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='materiais_equipamentos',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='bombeio',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='membros',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_fim_frente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_inicio_frente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='quantidade_bombeada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='Cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='GO.cliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='Unidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='GO.unidade'),
        ),
    ]
