# Generated by Django 5.2.5 on 2025-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0004_alter_ordemservico_numero_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='codigo_os',
            field=models.CharField(max_length=20),
        ),
    ]
