# Generated by Django 4.2.24 on 2025-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0004_relatorio_tecnico_delete_curva_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='pob_op',
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='avanco_total_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='bombeio_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='cambagem_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='compartimentos_limpos_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='ensacamento_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='gavetas_limpos_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='icamento_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='lavagem_fina_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='limpeza_mecanizada_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='liquidos_frente_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='pob_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='qtnd_sacos_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='qtnd_tambores_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='solidos_frente_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='total_hh_frente_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdoatividade',
            name='atividade',
            field=models.CharField(blank=True, choices=[('abertura pt', 'Abertura PT / Opening pt'), ('aferição de pressão arterial', 'Aferição de Pressão Arterial / Arterial Pressure Measurement'), ('almoço', 'Almoço / Lunch'), ('avaliação inicial da área de trabalho', 'Avaliação Inicial da Área de Trabalho / Pre-setup of the work area'), ('bombeio', 'Bombeio / Pump'), ('conferência do material e equipamento no container', 'Conferência do Material e Equipamento no Container / Checking the material and equipment in the container'), ('dds', 'DDS / Work Safety Dialog'), ('em espera', 'Em Espera / Stand-by'), ('acesso ao tanque', 'Acesso ao Tanque / Tank access'), ('equipe chegou no aeroporto', 'Equipe Chegou no Aeroporto / Team arrived at the airport'), ('vôo com destino a unidade', 'Vôo com Destino à Unidade / Flight to unity'), ('vôo postergado', 'Vôo Postergado / Flight postponed'), ('triagem', 'Triagem / Security screening'), ('check-in, pesagem, briefing', 'Check-in, Pesagem, Briefing / Check-in, weighing, briefing'), ('saída da base', 'Saída da Base / Departure from base'), ('equipe se apresenta ao responsável da unidade', 'Equipe se Apresenta ao Responsável da Unidade / The team presents itself to the person in charge of the unit'), ('instalação/preparação/montagem', 'Instalação/Preparação/Montagem / Setup'), ('jantar', 'Jantar / Dinner'), ('limpeza da área', 'Limpeza da Área / Housekeep'), ('treinamento de abandono', 'Treinamento de Abandono / Drill'), ('alarme real', 'Alarme Real / Real alarm'), ('instrução de segurança', 'Instrução de Segurança / Security instructions'), ('apoio à equipe de bordo nas atividades da unidade', 'Apoio à Equipe de Bordo nas Atividades da Unidade / Support to the onboard team in unit activities'), ('desmobilização do material - dentro do tanque', 'Desmobilização do Material - Dentro do Tanque / Material demobilization - Inside the tank'), ('desmobilização do material - fora do tanque', 'Desmobilização do Material - Fora do Tanque / Material demobilization - Outside the tank'), ('inventário', 'Inventário / Inventory'), ('mobilização de material - dentro do tanque', 'Mobilização de Material - Dentro do Tanque / Material mobilization - Inside the tank'), ('mobilização de material - fora do tanque', 'Mobilização de Material - Fora do Tanque / Material mobilization - Outside the tank'), ('realização de simulado de resgate', 'Realização de Simulado de Resgate / Execution of rescue drill'), ('limpeza e higienização de coifa', 'Limpeza e Higienização de Coifa / Cleaning and sanitization of the hood'), ('limpeza de dutos', 'Limpeza de Dutos / Duct cleaning'), ('coleta e análise de ar', 'Coleta e Análise de Ar / Air sampling and analysis'), ('cambagem', 'Cambagem / Camber'), ('içamento', 'Içamento / Lifting'), ('limpeza fina', 'Limpeza Fina / Washing'), ('manutenção de equipamentos - dentro do tanque', 'Manutenção de Equipamentos - Dentro do Tanque / Maintenance equipments - Inside the tank'), ('manutenção de equipamentos - fora do tanque', 'Manutenção de Equipamentos - Fora do Tanque / Maintenance equipments - Outside the tank'), ('jateamento', 'Jateamento / Blasting')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rdoatividade',
            name='ordem',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='avanco_total_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='bombeio_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='cambagem_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='compartimentos_limpos_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='ensacamento_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='gavetas_limpos_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='hh_disponivel_op',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='icamento_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='lavagem_fina_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='limpeza_mecanizada_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='liquidos_op_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='qtnd_sacos_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='qtnd_tambores_op',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='solidos_op_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='total_hh_op_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_tecnico',
            name='ultimo_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
