# Generated by Django 4.2.24 on 2025-10-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0005_remove_relatorio_tecnico_pob_op_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_tecnicos', to='GO.ordemservico'),
        ),
    ]
