# Generated by Django 4.2.24 on 2025-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0006_relatorio_tecnico_ordem_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='bombeio_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='cambagem_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='ensacamento_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='icamento_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='lavagem_fina_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='limpeza_mecanizada_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='mob_demob_peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_avanco_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_bombeio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_cambagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_ensacamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_icamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_lavagem_fina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_limpeza_mecanizada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio_tecnico',
            name='percentual_mob_demob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
