# Generated by Django 5.2.5 on 2025-08-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0006_ordemservico_staus_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='staus_comercial',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status_comercial',
            field=models.CharField(choices=[('Faturado', 'Faturado'), ('Em aberto', 'Em aberto'), ('Cancelado', 'Cancelado')], default='Em aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status_operacao',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Em Andamento', 'Em Andamento'), ('Paralizada', 'Paralizada'), ('Finalizada', 'Finalizada')], default='Programada', max_length=50),
        ),
    ]
