# Generated by Django 5.2.1 on 2025-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0007_remove_ordemservico_staus_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='servico',
            field=models.CharField(choices=[('limpeza de tanque de carga', 'limpeza de tanque de carga'), ('limpeza de tanque de slop', 'limpeza de tanque de slop'), ('limpeza de tanque de óleo', 'limpeza de tanque de óleo'), ('limpeza de tanque de água', 'limpeza de tanque de água'), ('limpeza de tanque de lama', 'limpeza de tanque de lama'), ('limpeza de tanque de retenção de drenagem', 'limpeza de tanque de retenção de drenagem'), ('limpeza de tanque de dreno', 'limpeza de tanque de dreno'), ('limpeza de tanque de lastro', 'limpeza de tanque de lastro'), ('limpeza de tanque de bilge', 'limpeza de tanque de bilge'), ('limpeza de tanque recovery', 'limpeza de tanque recovery'), ('limpeza de tanque de settling (óleo)', 'limpeza de tanque de settling (óleo)'), ('limpeza de tanque de diesel', 'limpeza de tanque de diesel'), ('limpeza de tanque de mgo', 'limpeza de tanque de mgo'), ('limpeza de tanque de sewage/esgoto', 'limpeza de tanque de sewage/esgoto'), ('limpeza de águas negras', 'limpeza de águas negras'), ('limpeza de águas cinzas', 'limpeza de águas cinzas'), ('limpeza de dutos', 'limpeza de dutos'), ('limpeza de coifa', 'limpeza de coifa'), ('coleta e análise do ar', 'coleta e análise do ar'), ('limpeza de lavanderia', 'limpeza de lavanderia'), ('limpeza (dutos + coifa)', 'limpeza (dutos + coifa)'), ('limpeza (dutos + coifa + coleta e análise de ar)', 'limpeza (dutos + coifa + coleta e análise de ar)'), ('limpeza (dutos + coifa + coleta e análise de ar + lavanderia)', 'limpeza (dutos + coifa + coleta e análise de ar + lavanderia)'), ('limpeza de vaso', 'limpeza de vaso'), ('limpeza da casa de bombas', 'limpeza da casa de bombas'), ('pintura', 'pintura'), ('desobstrução da linha de drenagem aberta', 'desobstrução da linha de drenagem aberta'), ('vigia', 'vigia'), ('serviço de irata', 'serviço de irata'), ('inventário, lista de verificação e planejamento dos materiais a bordo', 'inventário, lista de verificação e planejamento dos materiais a bordo'), ('emissão de free for fire', 'emissão de free for fire'), ('shut down', 'shut down')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tag',
            field=models.CharField(choices=[('LTC', 'LTC'), ('LTS', 'LTS'), ('LTO', 'LTO'), ('LTA', 'LTA'), ('LTL', 'LTL'), ('LRD', 'LRD'), ('LTD', 'LTD'), ('TLA', 'TLA'), ('LTB', 'LTB'), ('LTR', 'LTR'), ('LTS', 'LTS'), ('LTD', 'LTD'), ('MGO', 'MGO'), ('TSE', 'TSE'), ('LAN', 'LAN'), ('LAC', 'LAC'), ('LDD', 'LDD'), ('LCF', 'LCF'), ('CAA', 'CAA'), ('LDL', 'LDL'), ('LDC', 'LDC'), ('DCA', 'DCA'), ('DCL', 'DCL'), ('LDV', 'LDV'), ('LCB', 'LCB'), ('PIN', 'PIN'), ('DLD', 'DLD'), ('VIG', 'VIG'), ('SIR', 'SIR'), ('INV', 'INV'), ('FFF', 'FFF'), ('SHD', 'SHD')], max_length=3),
        ),
    ]
