# Generated by Django 4.2.24 on 2025-10-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0007_relatorio_tecnico_bombeio_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
            },
        ),
    ]
