# Generated by Django 4.2.24 on 2025-10-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0008_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='dias_de_operacao_frente',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
