# Generated by Django 4.2.24 on 2025-10-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0010_alter_ordemservico_dias_de_operacao_frente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='servicos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
