# Generated by Django 4.2.24 on 2025-10-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0011_ordemservico_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='servicos',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='servico',
            field=models.CharField(max_length=200),
        ),
    ]
