# Generated by Django 5.2.5 on 2025-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0011_alter_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='tag',
            field=models.CharField(blank=True, choices=[('ACO', 'ACO'), ('ART', 'ART'), ('CAT', 'CAT'), ('GFI', 'GFI'), ('GFE', 'GFE'), ('CAG', 'CAG'), ('CAA', 'CAA'), ('DER', 'DER'), ('DES', 'DES'), ('DPE', 'DPE'), ('DEQ', 'DEQ'), ('DEE', 'DEE'), ('EEQ', 'EEQ'), ('DBT', 'DBT'), ('DLD', 'DLD'), ('DEL', 'DEL'), ('DAO', 'DAO'), ('DCO', 'DCO'), ('CPP', 'CPP'), ('DRE', 'DRE'), ('DPR', 'DPR'), ('TST', 'TST'), ('EPM', 'EPM'), ('FFF', 'FFF'), ('ENR', 'ENR'), ('STB', 'STB'), ('EST', 'EST'), ('ERE', 'ERE'), ('FAL', 'FAL'), ('FAU', 'FAU'), ('FCV', 'FCV'), ('FCT', 'FCT'), ('FEL', 'FEL'), ('ENQ', 'ENQ'), ('EQC', 'EQC'), ('ALP', 'ALP'), ('ERS', 'ERS'), ('FIR', 'FIR'), ('FIN', 'FIN'), ('MAO', 'MAO'), ('MAT', 'MAT'), ('MEC', 'MEC'), ('QUI', 'QUI'), ('TEC', 'TEC'), ('EXT', 'EXT'), ('HAT', 'HAT'), ('INS', 'INS'), ('IBO', 'IBO'), ('INV', 'INV'), ('DCL', 'DCL'), ('DCA', 'DCA'), ('LDC', 'LDC'), ('LCB', 'LCB'), ('LAC', 'LAC'), ('LAN', 'LAN'), ('APP', 'APP'), ('LCF', 'LCF'), ('LCC', 'LCC'), ('VOI', 'VOI'), ('LDD', 'LDD'), ('DUT', 'DUT'), ('ARC', 'ARC'), ('EXC', 'EXC'), ('LDL', 'LDL'), ('SIL', 'SIL'), ('LTA', 'LTA'), ('LTB', 'LTB'), ('LTC', 'LTC'), ('LTD', 'LTD'), ('LDR', 'LDR'), ('LTL', 'LTL'), ('TLA', 'TLA'), ('MGO', 'MGO'), ('LTO', 'LTO'), ('LRD', 'LRD'), ('LTS', 'LTS'), ('TSE', 'TSE'), ('LSL', 'LSL'), ('LTR', 'LTR'), ('AGP', 'AGP'), ('LOD', 'LOD'), ('SLU', 'SLU'), ('LTG', 'LTG'), ('LDV', 'LDV'), ('VAS', 'VAS'), ('DEC', 'DEC'), ('LGE', 'LGE'), ('LTP', 'LTP'), ('LOE', 'LOE'), ('MES', 'MES'), ('MOE', 'MOE'), ('MOP', 'MOP'), ('MPE', 'MPE'), ('MDS', 'MDS'), ('PIN', 'PIN'), ('RAD', 'RAD'), ('REL', 'REL'), ('RPM', 'RPM'), ('SSI', 'SSI'), ('SIR', 'SIR'), ('SHD', 'SHD'), ('SUR', 'SUR'), ('TDA', 'TDA'), ('TDS', 'TDS'), ('TEO', 'TEO'), ('VIG', 'VIG')], max_length=3, null=True),
        ),
    ]
