# Generated by assistant to restore missing migration
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('GO', '0011_ordemservico_servicos'),
	]

	operations = [
		migrations.AddField(
			model_name='ordemservico',
			name='tanques',
			field=models.TextField(blank=True, null=True),
		),
	]

