# Generated by Django 5.2.5 on 2025-09-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0012_alter_ordemservico_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='metodo',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('Demais', 'Demais'), ('N/A', 'N/A')], max_length=20),
        ),
    ]
