# Generated by Django 5.2.4 on 2025-09-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0013_alter_ordemservico_metodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='detalhes',
            new_name='controle_de_atividades',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='materiais_equipamentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
