# Generated by Django 4.2.24 on 2025-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0013_alter_ordemservico_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='servicos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
