# Generated by Django 5.2.5 on 2025-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0014_rename_detalhes_ordemservico_controle_de_atividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='controle_de_atividades',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='materiais_equipamentos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
