# Generated by Django 4.2.24 on 2025-10-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0014_ordemservico_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='material',
            field=models.CharField(blank=True, choices=[('A Bordo', 'A Bordo'), ('Embarcar', 'Embarcar'), ('Desembarcar', 'Desembarcar')], max_length=20, null=True),
        ),
    ]
