# Generated by Django 5.2.6 on 2025-09-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0015_alter_ordemservico_controle_de_atividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='metodo_secundario',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('Demais', 'Demais'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
    ]
