# Generated by Django 4.2.24 on 2025-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0015_ordemservico_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='funcoes',
            field=models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Supervisor Irata', 'Supervisor Irata'), ('Eletricista', 'Eletricista'), ('Técnico de Segurança', 'Técnico de Segurança'), ('Ajudante', 'Ajudante'), ('Resgatista', 'Resgatista'), ('Mecânico', 'Mecânico')], max_length=50, null=True),
        ),
    ]
