# Generated by Django 4.2.24 on 2025-10-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0016_alter_rdo_funcoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='frente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='funcoes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
