# Generated by Django 4.2.24 on 2025-10-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0017_ordemservico_frente_alter_rdo_funcoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_de_inspeção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsável', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inspecao_material', models.DateField(blank=True, null=True)),
                ('local_inspecao', models.CharField(blank=True, max_length=100, null=True)),
                ('previsao_retorno', models.DateField(blank=True, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos_formulario_inspecao/')),
                ('equipamentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_de_inspecao', to='GO.equipamentos')),
            ],
        ),
    ]
