# Generated by Django 5.2.6 on 2025-09-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0017_cliente_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_comercial',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Em aberto', max_length=20),
        ),
    ]
