# Generated by Django 5.2.6 on 2025-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0018_alter_ordemservico_status_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_comercial',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Em aberto', max_length=20),
        ),
    ]
