# Generated by Django 4.2.24 on 2025-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0018_equipamentos_formulario_de_inspeção'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='vazao_bombeio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vazão de bombeio em m3/h (usada para calcular quantidade bombeada). Se vazio, usar 36 m3/h por padrão.', max_digits=8, null=True),
        ),
    ]
