# Generated by Django 5.2.6 on 2025-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0019_alter_ordemservico_status_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_operacao',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Em Andamento', 'Em Andamento'), ('Paralizada', 'Paralizada'), ('Finalizada - Equipamentos alocados', 'Finalizada - Equipamentos alocados'), ('Finalizada - 100%', 'Finalizada - 100%')], default='Programada', max_length=50),
        ),
    ]
