# Generated by Django 5.2.6 on 2025-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0020_alter_ordemservico_status_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_comercial',
            field=models.CharField(choices=[('Não Realizada', 'Não Realizada'), ('Periódica', 'Periódica'), ('Realizada', 'Realizada')], default='Em aberto', max_length=20),
        ),
    ]
