# Generated by Django 4.2.24 on 2025-10-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0020_merge_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='tanques',
        ),
    ]
