# Generated by Django 4.2.24 on 2025-10-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0021_remove_ordemservico_tanques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tanques',
            field=models.TextField(blank=True, null=True),
        ),
    ]
