# Generated by Django 4.2.24 on 2025-10-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0023_modelo_alter_equipamentos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='previsao_termino',
        ),
    ]
