# Generated by Django 4.2.24 on 2025-10-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0024_remove_rdo_previsao_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDOMembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('em_servico', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_rdo', to='GO.pessoa')),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='GO.rdo')),
            ],
            options={
                'verbose_name': 'Membro da Equipe do RDO',
                'verbose_name_plural': 'Membros da Equipe do RDO',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
