# Generated by Django 4.2.24 on 2025-10-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0025_rdomembroequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='funcoes_list',
            field=models.TextField(blank=True, help_text='Lista JSON de funções correspondentes aos membros', null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='membros',
            field=models.TextField(blank=True, help_text='Lista JSON de nomes dos membros da equipe (na ordem)', null=True),
        ),
    ]
