# Generated by Django 4.2.24 on 2025-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0026_rdo_funcoes_list_rdo_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='funcoes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='sentido_limpeza',
            field=models.BooleanField(blank=True, choices=[(True, 'vante > ré'), (False, 'ré > vante')], null=True),
        ),
    ]
