# Generated by Django 4.2.24 on 2025-10-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0027_alter_rdo_funcoes_alter_rdo_sentido_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='previsão_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
