# Generated by Django 4.2.24 on 2025-10-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0028_rdo_previsão_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_equipamento/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_equipamento', to='GO.equipamentos')),
            ],
            options={
                'verbose_name': 'Foto de Equipamento',
                'verbose_name_plural': 'Fotos de Equipamento',
            },
        ),
    ]
