# Generated by Django 4.2.24 on 2025-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0029_equipamentofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='embarcacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='numero_os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
