# Generated by Django 4.2.25 on 2025-10-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0030_equipamentos_cliente_equipamentos_embarcacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='modelo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='GO.modelo'),
        ),
    ]
