# Generated by Django 4.2.25 on 2025-10-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0031_equipamentos_modelo_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='bombeio_frente',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='bombeio_op',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='bombeio_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='cambagem_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='ensacamento_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='icamento_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='lavagem_fina_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='limpeza_mecanizada_peso',
        ),
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='mob_demob_peso',
        ),
    ]
