# Generated by Django 4.2.24 on 2025-10-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0032_remove_relatorio_tecnico_bombeio_frente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio_tecnico',
            name='percentual_bombeio',
        ),
    ]
