# Generated by Django 4.2.25 on 2025-10-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0033_remove_relatorio_tecnico_percentual_bombeio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='ec_times_json',
            field=models.TextField(blank=True, help_text='JSON com listas de entradas/saidas para espaço confinado', null=True),
        ),
    ]
