# Generated by Django 4.2.25 on 2025-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0034_rdo_ec_times_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='entrada_confinado_6',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='saida_confinado_6',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
