# Generated by Django 4.2.25 on 2025-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0035_rdo_entrada_confinado_1_rdo_entrada_confinado_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='previsão_termino',
        ),
        migrations.AddField(
            model_name='rdo',
            name='previsao_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
