# Generated by Django 4.2.25 on 2025-10-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0036_remove_rdo_previsão_termino_rdo_previsao_termino'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDOFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_rdo/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_rdo', to='GO.rdo')),
            ],
            options={
                'verbose_name': 'Foto do RDO',
                'verbose_name_plural': 'Fotos do RDO',
            },
        ),
    ]
