# Generated by Django 4.2.24 on 2025-10-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0038_delete_rdofoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDOFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos_rdo/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_rdo', to='GO.rdo')),
            ],
            options={
                'verbose_name': 'Foto de RDO',
                'verbose_name_plural': 'Fotos de RDO',
            },
        ),
    ]
