# Generated by Django 4.2.25 on 2025-10-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0039_rdofoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RDOFoto',
        ),
    ]
