# Generated by Django 4.2.24 on 2025-10-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0040_delete_rdofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='fotos_1',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rdo/'),
        ),
        migrations.AddField(
            model_name='rdo',
            name='fotos_2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rdo/'),
        ),
        migrations.AddField(
            model_name='rdo',
            name='fotos_3',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rdo/'),
        ),
        migrations.AddField(
            model_name='rdo',
            name='fotos_4',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rdo/'),
        ),
        migrations.AddField(
            model_name='rdo',
            name='fotos_5',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_rdo/'),
        ),
    ]
