# Generated by Django 4.2.25 on 2025-10-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0042_populate_fotos_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdo',
            old_name='fotos',
            new_name='fotos_img',
        ),
        migrations.AddField(
            model_name='rdo',
            name='fotos_json',
            field=models.TextField(blank=True, help_text='JSON array com paths/URLs das fotos (fotos unificadas)', null=True),
        ),
    ]
