# Generated by Django 4.2.24 on 2025-10-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0043_rename_fotos_rdo_fotos_img_rdo_fotos_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdo',
            old_name='ensacamento',
            new_name='avanco_total_cumulativo',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='tambores',
            new_name='avanco_total_frente',
        ),
        migrations.AddField(
            model_name='rdo',
            name='cambagem_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='cambagem_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='compartimentos_limpos_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='compartimentos_limpos_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='ensacamento_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='ensacamento_diario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='ensacamento_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='gavetas_limpos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='gavetas_limpos_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='hh_disponivel_cumulativo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='icamento_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='icamento_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='lavagem_fina_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='lavagem_fina_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='limpeza_mecanizada_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='limpeza_mecanizada_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='liquidos_cumulativo_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='liquidos_frente_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='pob_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='qtnd_sacos_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='qtnd_sacos_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='qtnd_tambores_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='qtnd_tambores_frente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='solidos_cumulativo_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='solidos_frente_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='tambores_diario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='total_hh_cumulativo_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='total_hh_frente_real',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='ultimo_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='metodo_exec',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Relatorio_tecnico',
        ),
    ]
