# Generated by Django 4.2.24 on 2025-10-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0044_rename_ensacamento_rdo_avanco_total_cumulativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdo',
            old_name='ensacamento_diario',
            new_name='ensacamento',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='tambores_diario',
            new_name='tambores',
        ),
    ]
