# Generated by Django 4.2.24 on 2025-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0045_rename_ensacamento_diario_rdo_ensacamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='tambores',
            field=models.IntegerField(blank=True, editable=False, help_text='Calculado automaticamente: ceil(ensacamento / 10)', null=True),
        ),
    ]
