# Generated by Django 4.2.24 on 2025-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0046_alter_rdo_tambores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='po',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='vazao_bombeio',
        ),
        migrations.AlterField(
            model_name='rdo',
            name='metodo_exec',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('Demais', 'Demais'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='tempo_uso_bomba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
