# Generated by Django 4.2.24 on 2025-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0047_remove_ordemservico_po_remove_rdo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
