# Generated by Django 4.2.25 on 2025-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0049_remove_rdo_data_rdo_vazao_bombeio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='vazao_bombeio',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='po',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='metodo_exec',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada')], max_length=20, null=True),
        ),
    ]
