# Generated by Django 4.2.25 on 2025-10-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0050_remove_rdo_vazao_bombeio_ordemservico_po_rdo_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdo',
            old_name='avanco_total_frente',
            new_name='avanco_total',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='cambagem_frente',
            new_name='cambagem',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='compartimentos_limpos_frente',
            new_name='cambagem_previsao',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='ensacamento_frente',
            new_name='ensacamento_previsao',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='gavetas_limpos',
            new_name='icamento',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='icamento_frente',
            new_name='icamento_previsao',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='lavagem_fina_cumulativo',
            new_name='percentual_limpeza_cumulativo',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='lavagem_fina_frente',
            new_name='percentual_limpeza_fina',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='limpeza_mecanizada_cumulativo',
            new_name='percentual_limpeza_fina_cumulativo',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='limpeza_mecanizada_frente',
            new_name='pob',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='liquidos_frente_m3',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='pob_frente',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='qtnd_sacos_frente',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='qtnd_tambores_frente',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='solidos_frente_m3',
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_limpeza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
