# Generated by Django 4.2.25 on 2025-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0051_rename_avanco_total_frente_rdo_avanco_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='percentual_cambagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_ensacamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_icamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
