# Generated by Django 4.2.24 on 2025-10-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0052_rdo_percentual_cambagem_rdo_percentual_ensacamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='compartimentos_limpos_cumulativo',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='gavetas_limpos_cumulativo',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='liquidos_cumulativo_m3',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='qtnd_sacos_cumulativo',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='qtnd_tambores_cumulativo',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='solidos_cumulativo_m3',
        ),
    ]
