# Generated by Django 4.2.24 on 2025-10-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0053_remove_rdo_compartimentos_limpos_cumulativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdo',
            old_name='avanco_total',
            new_name='percentual_avanco',
        ),
        migrations.RenameField(
            model_name='rdo',
            old_name='avanco_total_cumulativo',
            new_name='percentual_avanco_cumulativo',
        ),
    ]
