# Generated by Django 4.2.25 on 2025-10-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0054_rename_avanco_total_rdo_percentual_avanco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='compartimentos_avanco_json',
            field=models.TextField(blank=True, help_text='JSON object com valores por compartimento (mecanizada/fina)', null=True),
        ),
    ]
