# Generated by Django 4.2.25 on 2025-10-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0055_rdo_compartimentos_avanco_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='limpeza_fina_cumulativa',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza fina informado pelo supervisor (percentual inteiro)', null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='limpeza_fina_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor diário inserido pelo supervisor para limpeza fina (percentual)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='limpeza_mecanizada_cumulativa',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza mecanizada informado pelo supervisor (percentual inteiro)', null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='limpeza_mecanizada_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor diário inserido pelo supervisor para limpeza mecanizada (percentual)', max_digits=5, null=True),
        ),
    ]
