# Generated by Django 4.2.25 on 2025-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0056_rdo_limpeza_fina_cumulativa_rdo_limpeza_fina_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='percentual_limpeza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
