# Generated by Django 4.2.25 on 2025-10-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0057_alter_rdo_percentual_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='bombeio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
