# Generated by Django 4.2.25 on 2025-10-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0058_rdo_bombeio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdomembroequipe',
            options={},
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='em_servico',
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='rdomembroequipe',
            name='rdo',
        ),
        migrations.AlterField(
            model_name='rdoatividade',
            name='atividade',
            field=models.CharField(blank=True, choices=[('abertura pt', 'Abertura PT / Opening pt'), ('aferição de pressão arterial', 'Aferição de Pressão Arterial / Arterial Pressure Measurement'), ('almoço', 'Almoço / Lunch'), ('avaliação inicial da área de trabalho', 'Avaliação Inicial da Área de Trabalho / Pre-setup of the work area'), ('conferência do material e equipamento no container', 'Conferência do Material e Equipamento no Container / Checking the material and equipment in the container'), ('dds', 'DDS / Work Safety Dialog'), ('em espera', 'Em Espera / Stand-by'), ('acesso ao tanque', 'Acesso ao Tanque / Tank access'), ('equipe chegou no aeroporto', 'Equipe Chegou no Aeroporto / Team arrived at the airport'), ('vôo com destino a unidade', 'Vôo com Destino à Unidade / Flight to unity'), ('vôo postergado', 'Vôo Postergado / Flight postponed'), ('triagem', 'Triagem / Security screening'), ('check-in, pesagem, briefing', 'Check-in, Pesagem, Briefing / Check-in, weighing, briefing'), ('saída da base', 'Saída da Base / Departure from base'), ('equipe se apresenta ao responsável da unidade', 'Equipe se Apresenta ao Responsável da Unidade / The team presents itself to the person in charge of the unit'), ('instalação/preparação/montagem', 'Instalação/Preparação/Montagem / Setup'), ('jantar', 'Jantar / Dinner'), ('limpeza da área', 'Limpeza da Área / Housekeep'), ('treinamento de abandono', 'Treinamento de Abandono / Drill'), ('alarme real', 'Alarme Real / Real alarm'), ('instrução de segurança', 'Instrução de Segurança / Security instructions'), ('apoio à equipe de bordo nas atividades da unidade', 'Apoio à Equipe de Bordo nas Atividades da Unidade / Support to the onboard team in unit activities'), ('desmobilização do material - dentro do tanque', 'Desmobilização do Material - Dentro do Tanque / Material demobilization - Inside the tank'), ('desmobilização do material - fora do tanque', 'Desmobilização do Material - Fora do Tanque / Material demobilization - Outside the tank'), ('inventário', 'Inventário / Inventory'), ('mobilização de material - dentro do tanque', 'Mobilização de Material - Dentro do Tanque / Material mobilization - Inside the tank'), ('mobilização de material - fora do tanque', 'Mobilização de Material - Fora do Tanque / Material mobilization - Outside the tank'), ('realização de simulado de resgate', 'Realização de Simulado de Resgate / Execution of rescue drill'), ('limpeza e higienização de coifa', 'Limpeza e Higienização de Coifa / Cleaning and sanitization of the hood'), ('limpeza de dutos', 'Limpeza de Dutos / Duct cleaning'), ('coleta e análise de ar', 'Coleta e Análise de Ar / Air sampling and analysis'), ('manutenção de equipamentos - dentro do tanque', 'Manutenção de Equipamentos - Dentro do Tanque / Maintenance equipments - Inside the tank'), ('manutenção de equipamentos - fora do tanque', 'Manutenção de Equipamentos - Fora do Tanque / Maintenance equipments - Outside the tank'), ('jateamento', 'Jateamento / Blasting')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RDOTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanque_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_tanque', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_tanque', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_compartimentos', models.IntegerField(blank=True, null=True)),
                ('gavetas', models.IntegerField(blank=True, null=True)),
                ('patamar', models.IntegerField(blank=True, null=True)),
                ('volume_tanque_exec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('servico_exec', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_exec', models.CharField(blank=True, max_length=50, null=True)),
                ('espaco_confinado', models.CharField(blank=True, max_length=10, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('em_servico', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_rdo', to='GO.pessoa')),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='GO.rdo')),
            ],
            options={
                'verbose_name': 'Membro da Equipe do RDO',
                'verbose_name_plural': 'Membros da Equipe do RDO',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
