# Generated by Django 4.2.24 on 2025-10-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0059_alter_rdomembroequipe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdomembroequipe',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Membro da Equipe do RDO', 'verbose_name_plural': 'Membros da Equipe do RDO'},
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='em_servico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_rdo', to='GO.pessoa'),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='rdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='GO.rdo'),
        ),
        migrations.DeleteModel(
            name='RDOTanque',
        ),
    ]
