# Generated by Django 4.2.25 on 2025-10-28 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0060_alter_rdomembroequipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanque_codigo', models.CharField(blank=True, max_length=120, null=True)),
                ('nome_tanque', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_tanque', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_compartimentos', models.IntegerField(blank=True, null=True)),
                ('gavetas', models.IntegerField(blank=True, null=True)),
                ('patamares', models.IntegerField(blank=True, null=True)),
                ('volume_tanque_exec', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('servico_exec', models.CharField(blank=True, max_length=80, null=True)),
                ('metodo_exec', models.CharField(blank=True, max_length=80, null=True)),
                ('espaco_confinado', models.CharField(blank=True, max_length=20, null=True)),
                ('operadores_simultaneos', models.IntegerField(blank=True, null=True)),
                ('h2s_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('lel', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('co_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('o2_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('total_n_efetivo_confinado', models.IntegerField(blank=True, null=True)),
                ('tempo_bomba', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ensacamento_dia', models.IntegerField(blank=True, null=True)),
                ('icamento_dia', models.IntegerField(blank=True, null=True)),
                ('cambagem_dia', models.IntegerField(blank=True, null=True)),
                ('tambores_dia', models.IntegerField(blank=True, null=True)),
                ('residuos_solidos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('residuos_totais', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('avanco_limpeza', models.CharField(blank=True, max_length=30, null=True)),
                ('avanco_limpeza_fina', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='GO.rdo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
