# Generated by Django 4.2.25 on 2025-10-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0061_rdotanque'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rdo',
            constraint=models.UniqueConstraint(fields=('ordem_servico', 'rdo'), name='unique_ordemservico_rdo'),
        ),
    ]
