# Generated by Django 4.2.24 on 2025-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0062_rdo_unique_ordemservico_rdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='tanque',
            field=models.CharField(blank=True, help_text='Nome/código do tanque (campo canônico adicionado)', max_length=120, null=True),
        ),
    ]
