# Generated by Django 4.2.24 on 2025-10-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0063_rdotanque_tanque'),
    ]

    operations = [
    ]
