# Generated by Django 4.2.24 on 2025-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0064_backfill_rdotanque_tanque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdotanque',
            name='tanque',
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_limpeza_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo canônico para percentuais diários de limpeza mecanizada (substitui legado)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_limpeza_fina_diario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo canônico para percentuais diários de limpeza fina (substitui legado)', max_digits=5, null=True),
        ),
    ]
