# Generated by Django 4.2.24 on 2025-10-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0065_remove_rdotanque_tanque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='percentual_limpeza',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='percentual_limpeza_cumulativo',
        ),
    ]
