# Generated by Django 4.2.25 on 2025-10-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0066_remove_rdo_percentual_limpeza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='percentual_limpeza_fina_diario',
        ),
        migrations.AddField(
            model_name='rdo',
            name='percentual_limpeza_mirror',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo espelho persistente com o valor visível no modal Supervisor (persistido via JS)', max_digits=5, null=True),
        ),
    ]
