# Generated by Django 4.2.25 on 2025-10-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0067_remove_rdo_percentual_limpeza_fina_diario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='percentual_limpeza_mirror',
        ),
    ]
