# Generated by Django 4.2.24 on 2025-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0068_remove_rdo_percentual_limpeza_mirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='percentual_limpeza_diario_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo canônico para percentuais de limpeza mecanizada cumulativos (média por compartimento)', max_digits=5, null=True),
        ),
    ]
