# Generated by Django 4.2.24 on 2025-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0069_rdo_percentual_limpeza_diario_cumulativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='link_logistica',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
