# Generated by Django 4.2.24 on 2025-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0070_ordemservico_link_logistica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='link_logistica',
            field=models.URLField(blank=True, default='', max_length=300, null=True),
        ),
    ]
