# Generated by Django 4.2.25 on 2025-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0071_alter_ordemservico_link_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='sentido_limpeza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
