# Generated by Django 4.2.25 on 2025-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0072_rdotanque_sentido_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_avanco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_cambagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_ensacamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_icamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_limpeza_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_limpeza_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_limpeza_fina_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_limpeza_fina_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
