# Generated by Django 4.2.25 on 2025-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0073_rdotanque_percentual_avanco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='bombeio',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='total_liquido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='sentido_limpeza',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
