# Generated by Django 4.2.24 on 2025-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0074_rdotanque_bombeio_rdotanque_total_liquido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='link_logistica',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
