# Generated by Django 4.2.24 on 2025-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0075_alter_ordemservico_link_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='cambagem_prev',
            field=models.IntegerField(blank=True, help_text='Previsão de cambagem por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='ensacamento_prev',
            field=models.IntegerField(blank=True, help_text='Previsão de ensacamento por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='icamento_prev',
            field=models.IntegerField(blank=True, help_text='Previsão de içamento por tanque', null=True),
        ),
    ]
