# Generated by Django 4.2.25 on 2025-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0076_rdotanque_cambagem_prev_rdotanque_ensacamento_prev_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_fina_cumulativa',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza fina informado pelo supervisor (percentual inteiro) por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_fina_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor diário inserido pelo supervisor para limpeza fina (percentual) por tanque', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_mecanizada_cumulativa',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza mecanizada informado pelo supervisor (percentual inteiro) por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_mecanizada_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor diário inserido pelo supervisor para limpeza mecanizada (percentual) por tanque', max_digits=5, null=True),
        ),
    ]
