# Generated by Django 4.2.24 on 2025-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0077_rdotanque_limpeza_fina_cumulativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_limpeza_fina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
