# Generated by Django on 2025-11-04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0078_rdotanque_percentual_limpeza_fina'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='compartimentos_avanco_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
