# Generated by Django 4.2.24 on 2025-11-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0079_rdotanque_compartimentos_avanco_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_fina_cumulativa_tanque',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza fina (percentual inteiro) — por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_manual_cumulativa_tanque',
            field=models.IntegerField(blank=True, help_text='Acumulado de limpeza manual (percentual inteiro) — por tanque', null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_manual_diaria_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor diário inserido pelo supervisor para limpeza manual (percentual) — por tanque', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_mecanizada_cumulativa',
            field=models.IntegerField(blank=True, help_text='[DEPRECATED] Acumulado (mecanizada) por tanque — usar limpeza_manual_cumulativa_tanque', null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_mecanizada_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Valor diário (mecanizada) por tanque — usar limpeza_manual_diaria_tanque', max_digits=5, null=True),
        ),
    ]
