# Generated by Django 4.2.25 on 2025-11-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0080_rdotanque_limpeza_fina_cumulativa_tanque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdotanque',
            name='limpeza_mecanizada_diaria',
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_fina_cumulativa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_fina_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_mecanizada_cumulativa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
