# Generated by Django 4.2.25 on 2025-11-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0081_remove_rdotanque_limpeza_mecanizada_diaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdotanque',
            name='limpeza_fina_cumulativa_tanque',
        ),
        migrations.RemoveField(
            model_name='rdotanque',
            name='limpeza_manual_cumulativa_tanque',
        ),
        migrations.RemoveField(
            model_name='rdotanque',
            name='limpeza_manual_diaria_tanque',
        ),
    ]
