# Generated by Django 4.2.25 on 2025-11-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0082_remove_rdotanque_limpeza_fina_cumulativa_tanque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='cambagem_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='ensacamento_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdotanque',
            name='icamento_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
