# Generated by Django 4.2.25 on 2025-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0083_rdotanque_cambagem_cumulativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='limpeza_mecanizada_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
