# Generated by Django 4.2.25 on 2025-11-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0084_rdotanque_limpeza_mecanizada_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='percentual_avanco_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
