# Generated by Django 4.2.25 on 2025-11-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0085_rdotanque_percentual_avanco_cumulativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_fina_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acumulado de limpeza fina informado pelo supervisor (percentual, 2 casas)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_mecanizada_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acumulado de limpeza mecanizada informado pelo supervisor (percentual, 2 casas)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_avanco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_avanco_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_limpeza_fina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_limpeza_fina_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
