# Generated by Django 4.2.24 on 2025-11-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0086_alter_rdo_limpeza_fina_cumulativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_fina_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='limpeza_mecanizada_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='percentual_avanco_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='percentual_limpeza_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='percentual_limpeza_fina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='percentual_limpeza_fina_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
