# Generated by Django 4.2.25 on 2025-11-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0087_alter_rdotanque_limpeza_fina_cumulativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('SUPERVISOR IRATA', 'SUPERVISOR IRATA'), ('ELETRICISTA', 'ELETRICISTA'), ('TÉCNICO DE SEGURANÇA', 'TÉCNICO DE SEGURANÇA'), ('AJUDANTE', 'AJUDANTE'), ('RESGATISTA', 'RESGATISTA'), ('MECÂNICO', 'MECÂNICO')], max_length=100),
        ),
    ]
