# Generated by Django 4.2.25 on 2025-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0088_alter_pessoa_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='sentido_limpeza',
            field=models.CharField(blank=True, choices=[('vante > ré', 'vante > ré'), ('ré > vante', 'ré > vante'), ('bombordo > boreste', 'bombordo > boreste'), ('boreste < bombordo', 'boreste < bombordo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='sentido_limpeza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
