# Generated by Django 4.2.24 on 2025-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0089_alter_rdo_sentido_limpeza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdotanque',
            name='sentido_limpeza',
            field=models.CharField(blank=True, choices=[('vante > ré', 'Vante > Ré'), ('ré > vante', 'Ré > Vante'), ('bombordo > boreste', 'Bombordo > Boreste'), ('boreste < bombordo', 'Boreste < Bombordo')], max_length=30, null=True),
        ),
    ]
