# Generated by Django 4.2.24 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0092_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='supervisores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
