# Generated by Django 4.2.25 on 2025-12-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0093_ordemservico_supervisores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='supervisores',
        ),
    ]
