# Generated by Django 4.2.24 on 2025-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0095_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='turno',
            field=models.CharField(blank=True, choices=[('Diurno', 'Diurno'), ('Noturno', 'Noturno')], max_length=20, null=True),
        ),
    ]
