# Generated by Django 4.2.24 on 2025-12-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0098_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='link_logistica',
        ),
    ]
