# Generated by Django 4.2.24 on 2025-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0099_remove_ordemservico_link_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status_planejamento',
            field=models.CharField(blank=True, choices=[('pendente', 'pendente'), ('em andamento', 'em andamento'), ('concluído', 'concluído')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='metodo',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('N/A', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='metodo_secundario',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('Roto rooter', 'Roto rooter'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='servico',
            field=models.CharField(choices=[('LIMPEZA DE TANQUE DE ÁGUA', 'LIMPEZA DE TANQUE DE ÁGUA'), ('LIMPEZA DE TANQUE DE DIESEL', 'LIMPEZA DE TANQUE DE DIESEL'), ('LIMPEZA DE TANQUE DE ÓLEO', 'LIMPEZA DE TANQUE DE ÓLEO'), ('LIMPEZA DE TANQUE DE DRENO', 'LIMPEZA DE TANQUE DE DRENO'), ('LIMPEZA DE TANQUE SEWAGE', 'LIMPEZA DE TANQUE SEWAGE'), ('LIMPEZA DE TANQUE DE PRODUTO QUÍMICO', 'LIMPEZA DE TANQUE DE PRODUTO QUÍMICO'), ('DESOBSTRUÇÃO DE LINHAS', 'DESOBSTRUÇÃO DE LINHAS'), ('DESOBSTRUÇÃO DE RALOS', 'DESOBSTRUÇÃO DE RALOS'), ('LIMPEZA DE DUTO', 'LIMPEZA DE DUTO'), ('LIMPEZA DE DUTO, COIFA', 'LIMPEZA DE DUTO, COIFA'), ('LIMPEZA DE DUTO, COIFA, COLETA DE AR', 'LIMPEZA DE DUTO, COIFA, COLETA DE AR'), ('COLETA DE AR', 'COLETA DE AR'), ('LIMPEZA DE COIFA', 'LIMPEZA DE COIFA'), ('LIMPEZA TROCADOR DE CALOR', 'LIMPEZA TROCADOR DE CALOR'), ('LIMPEZA QUÍMICA DE TUBULAÇÃO', 'LIMPEZA QUÍMICA DE TUBULAÇÃO'), ('LIMPEZA DE TANQUE DE LAMA', 'LIMPEZA DE TANQUE DE LAMA'), ('MOBILIZAÇÃO/DESMOBILIZAÇÃO DE TANQUE', 'MOBILIZAÇÃO/DESMOBILIZAÇÃO DE TANQUE'), ('LIMPEZA DE VASO', 'LIMPEZA DE VASO'), ("LIMPEZA DE CAIXA D'ÁGUA/BEBEDOURO", "LIMPEZA DE CAIXA D'ÁGUA/BEBEDOURO"), ('EMISSÃO DE FREE FOR FIRE', 'EMISSÃO DE FREE FOR FIRE'), ('COLETA DE ÁGUA', 'COLETA DE ÁGUA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='servico_rdo',
            field=models.CharField(blank=True, choices=[('LIMPEZA DE TANQUE DE ÁGUA', 'LIMPEZA DE TANQUE DE ÁGUA'), ('LIMPEZA DE TANQUE DE DIESEL', 'LIMPEZA DE TANQUE DE DIESEL'), ('LIMPEZA DE TANQUE DE ÓLEO', 'LIMPEZA DE TANQUE DE ÓLEO'), ('LIMPEZA DE TANQUE DE DRENO', 'LIMPEZA DE TANQUE DE DRENO'), ('LIMPEZA DE TANQUE SEWAGE', 'LIMPEZA DE TANQUE SEWAGE'), ('LIMPEZA DE TANQUE DE PRODUTO QUÍMICO', 'LIMPEZA DE TANQUE DE PRODUTO QUÍMICO'), ('DESOBSTRUÇÃO DE LINHAS', 'DESOBSTRUÇÃO DE LINHAS'), ('DESOBSTRUÇÃO DE RALOS', 'DESOBSTRUÇÃO DE RALOS'), ('LIMPEZA DE DUTO', 'LIMPEZA DE DUTO'), ('LIMPEZA DE DUTO, COIFA', 'LIMPEZA DE DUTO, COIFA'), ('LIMPEZA DE DUTO, COIFA, COLETA DE AR', 'LIMPEZA DE DUTO, COIFA, COLETA DE AR'), ('COLETA DE AR', 'COLETA DE AR'), ('LIMPEZA DE COIFA', 'LIMPEZA DE COIFA'), ('LIMPEZA TROCADOR DE CALOR', 'LIMPEZA TROCADOR DE CALOR'), ('LIMPEZA QUÍMICA DE TUBULAÇÃO', 'LIMPEZA QUÍMICA DE TUBULAÇÃO'), ('LIMPEZA DE TANQUE DE LAMA', 'LIMPEZA DE TANQUE DE LAMA'), ('MOBILIZAÇÃO/DESMOBILIZAÇÃO DE TANQUE', 'MOBILIZAÇÃO/DESMOBILIZAÇÃO DE TANQUE'), ('LIMPEZA DE VASO', 'LIMPEZA DE VASO'), ("LIMPEZA DE CAIXA D'ÁGUA/BEBEDOURO", "LIMPEZA DE CAIXA D'ÁGUA/BEBEDOURO"), ('EMISSÃO DE FREE FOR FIRE', 'EMISSÃO DE FREE FOR FIRE'), ('COLETA DE ÁGUA', 'COLETA DE ÁGUA')], max_length=100, null=True),
        ),
    ]
