# Generated by Django 4.2.24 on 2025-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0100_ordemservico_status_planejamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='metodo',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('N/A', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='metodo_secundario',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Mecanizada', 'Mecanizada'), ('Robotizada', 'Robotizada'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
    ]
