# Generated by Django 4.2.24 on 2025-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0101_alter_ordemservico_metodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_planejamento',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Pendente', max_length=50, null=True),
        ),
    ]
