# Generated by Django 4.2.25 on 2025-12-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0105_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='observacoes_cliente_en',
            field=models.TextField(blank=True, help_text='Customer notes (English)', null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='observacoes_cliente_pt',
            field=models.TextField(blank=True, help_text='Observações do cliente (Português)', null=True),
        ),
    ]
