# Generated by Django 4.2.25 on 2025-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0106_rdo_observacoes_cliente_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='observacoes_cliente_en',
        ),
        migrations.RemoveField(
            model_name='rdo',
            name='observacoes_cliente_pt',
        ),
        migrations.AddField(
            model_name='rdo',
            name='ciente_observacoes_en',
            field=models.TextField(blank=True, help_text='Texto traduzido automaticamente (EN)', null=True),
        ),
        migrations.AddField(
            model_name='rdo',
            name='ciente_observacoes_pt',
            field=models.TextField(blank=True, help_text='Texto que indica ciência das observações (PT)', null=True),
        ),
    ]
