# Generated by Django 4.2.25 on 2025-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0107_remove_rdo_observacoes_cliente_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='pt_manha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='pt_noite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='pt_tarde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
