# Generated by Django 4.2.25 on 2025-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0108_alter_rdo_pt_manha_alter_rdo_pt_noite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='fotos_1',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_2',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_3',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_4',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_5',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_img',
            field=models.ImageField(blank=True, null=True, upload_to='rdos/'),
        ),
    ]
