# Generated by Django 4.2.25 on 2025-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0109_alter_rdo_fotos_1_alter_rdo_fotos_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='previsao_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
