# Generated by Django 4.2.25 on 2025-12-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0110_rdotanque_previsao_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='total_liquido',
        ),
        migrations.RemoveField(
            model_name='rdotanque',
            name='previsao_termino',
        ),
    ]
