# Generated by Django 4.2.25 on 2025-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0111_remove_rdo_total_liquido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='total_liquido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
