# Generated by Django 4.2.24 on 2025-12-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0112_rdo_total_liquido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='previsao_termino',
        ),
    ]
