# Generated by Django 4.2.25 on 2026-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0120_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorCanonical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=150, unique=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coordenador Canônico',
                'verbose_name_plural': 'Coordenadores Canônicos',
            },
        ),
    ]
