# Generated by Django 4.2.24 on 2026-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0122_alter_ordemservico_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdotanque',
            name='tambores_cumulativo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
