# Generated by Django 4.2.25 on 2026-01-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0125_alter_ordemservico_servico_alter_rdo_servico_rdo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status_geral',
            field=models.CharField(blank=True, choices=[('Programada', 'Programada'), ('Em Andamento', 'Em Andamento'), ('Paralizada', 'Paralizada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status_operacao',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Em Andamento', 'Em Andamento'), ('Paralizada', 'Paralizada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=50),
        ),
    ]
