# Generated by Django 4.2.25 on 2026-01-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0081_merge_duplicate_tanques'),
        ('GO', '0128_alter_rdoatividade_atividade'),
    ]

    operations = [
    ]
