# Generated by Django 4.2.25 on 2026-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0129_merge_20260114_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='tambores',
            field=models.IntegerField(blank=True, help_text='Valor manual (anteriormente calculado automaticamente).', null=True),
        ),
    ]
