# Generated by Django 4.2.25 on 2026-01-19 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0131_alter_cliente_options_alter_unidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_supervisionadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
