# Generated by Django 4.2.25 on 2026-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0132_alter_ordemservico_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterField(
            model_name='rdo',
            name='ec_times_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='sentido_limpeza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
