# Generated by Django 4.2.25 on 2026-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0133_alter_pessoa_options_alter_rdo_ec_times_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='coordenadorcanonical',
            options={'verbose_name_plural': 'Coordenadores Canônicos'},
        ),
        migrations.AlterModelOptions(
            name='equipamentofoto',
            options={'verbose_name_plural': 'Fotos de Equipamento'},
        ),
        migrations.AlterModelOptions(
            name='equipamentos',
            options={'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='funcao',
            options={'verbose_name_plural': 'Funções'},
        ),
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name_plural': 'Modelos de Equipamento'},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['-data_inicio', 'numero_os'], 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='rdoatividade',
            options={'ordering': ['ordem'], 'verbose_name_plural': 'Atividades de RDO'},
        ),
        migrations.AlterModelOptions(
            name='rdomembroequipe',
            options={'ordering': ['ordem', 'id'], 'verbose_name_plural': 'Membros da Equipe do RDO'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_certificado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status_databook',
            field=models.TextField(blank=True, choices=[('Não Aplicável', 'Não Aplicável'), ('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado')], null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='ciente_observacoes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='ciente_observacoes_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='compartimentos_avanco_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='fotos_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='funcoes_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_fina_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_fina_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_mecanizada_cumulativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='limpeza_mecanizada_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='membros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_limpeza_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='percentual_limpeza_diario_cumulativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='sentido_limpeza',
            field=models.CharField(blank=True, choices=[('vante > ré', 'vante > ré'), ('ré > vante', 'ré > vante'), ('bombordo > boreste', 'bombordo > boreste'), ('boreste < bombordo', 'boreste < bombordo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rdo',
            name='tambores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='cambagem_prev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='ensacamento_prev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdotanque',
            name='icamento_prev',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
