# Generated by Django 4.2.25 on 2026-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0135_alter_ordemservico_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='confinado',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default='Não'),
        ),
    ]
