# Generated by Django 4.2.25 on 2026-02-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0141_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='coordenador',
            field=models.CharField(choices=[('JORGE VINICIUS SIQUEIRA LUCAS SILVA', 'JORGE VINICIUS SIQUEIRA LUCAS SILVA'), ('RICARDO PIRES DE MOURA JUNIOR', 'RICARDO PIRES DE MOURA JUNIOR'), ('KETLEY BARBOSA', 'KETLEY BARBOSA'), ('THALES MENEZES', 'THALES MENEZES'), ('MARCOS CORREIA', 'MARCOS CORREIA'), ('GABRIEL DELAIA', 'GABRIEL DELAIA'), ('AILTON OLIVEIRA', 'AILTON OLIVEIRA'), ('ANDRE SANTIAGO', 'ANDRE SANTIAGO'), ('JONATHAN LIMA LOUZADA', 'JONATHAN LIMA LOUZADA'), ('C-SAFETY / LOCAÇÃO', 'C-SAFETY / LOCAÇÃO'), ('MARCOS DELGADO', 'MARCOS DELGADO')], max_length=50, null=True),
        ),
    ]
