# Generated by Django 4.2.25 on 2026-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0144_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='coordenador',
            field=models.CharField(choices=[('', '--- Selecione um coordenador ---'), ('JORGE VINICIUS SIQUEIRA LUCAS SILVA', 'JORGE VINICIUS SIQUEIRA LUCAS SILVA'), ('RICARDO PIRES DE MOURA JUNIOR', 'RICARDO PIRES DE MOURA JUNIOR'), ('KETLEY BARBOSA', 'KETLEY BARBOSA'), ('MARCOS CORREIA', 'MARCOS CORREIA'), ('GABRIEL DELAIA', 'GABRIEL DELAIA'), ('ANDRE SANTIAGO', 'ANDRE SANTIAGO'), ('IVONEI DE SOUZA', 'IVONEI DE SOUZA'), ('JONATHAN LIMA LOUZADA', 'JONATHAN LIMA LOUZADA'), ('C-SAFETY / LOCAÇÃO', 'C-SAFETY / LOCAÇÃO'), ('MARCOS DELGADO', 'MARCOS DELGADO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
