# Generated by Django 4.2.25 on 2026-02-19 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0146_mobilesyncevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=120, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mobile API Tokens',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='GO_mobileap_user_id_3cc079_idx'), models.Index(fields=['expires_at'], name='GO_mobileap_expires_2978d2_idx')],
            },
        ),
    ]
