# Generated by Django 4.2.25 on 2026-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0149_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='situacao',
            field=models.CharField(blank=True, choices=[('embarcardo', 'Embarcado'), ('trocou_unidade', 'Trocou de Unidade'), ('retornou_base', 'Retornou para Base')], max_length=30, null=True),
        ),
    ]
