# Generated by Django 4.2.25 on 2026-03-04 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0150_equipamentos_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoSituacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.CharField(blank=True, max_length=30, null=True)),
                ('current', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacao_logs', to='GO.equipamentos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
