# Generated by Django 4.2.25 on 2026-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0151_equipamentosituacaolog'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipamentos',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_tag__isnull', False), models.Q(('numero_tag', ''), _negated=True)), fields=('numero_tag',), name='uniq_equip_numero_tag_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='equipamentos',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_serie__isnull', False), models.Q(('numero_serie', ''), _negated=True)), fields=('numero_serie',), name='uniq_equip_numero_serie_not_blank'),
        ),
    ]
