# Generated by Django 4.2.25 on 2026-03-05 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0152_equipamentos_uniq_equip_numero_tag_not_blank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoIdentificadorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('tag', 'TAG'), ('serie', 'Número de Série')], max_length=10)),
                ('previous_value', models.CharField(blank=True, max_length=100, null=True)),
                ('current_value', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificador_logs', to='GO.equipamentos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
