# Generated by Django 4.2.23 on 2026-07-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0158_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('proposta', models.IntegerField(primary_key=True, serialize=False)),
                ('revisao', models.IntegerField()),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_solicitacao_proposta', models.DateField()),
                ('data_fechamento_proposta', models.DateField(blank=True, null=True)),
                ('previsao_contratacao', models.DateField()),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('natureza', models.CharField(choices=[('Aditivo', 'Aditivo'), ('Reajuste', 'Reajuste'), ('Spot', 'Spot'), ('Contrato Novo', 'Contrato Novo'), ('Renovação', 'Renovação')], max_length=50)),
                ('heat_map', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('motivo_perda', models.CharField(choices=[('Governo', 'Governo'), ('Desistência do cliente', 'Desistência do cliente'), ('Fora do Escopo', 'Fora do Escopo'), ('Diretriz Estratégica', 'Diretriz Estratégica'), ('Prazo', 'Prazo'), ('Operações', 'Operações'), ('Demanda Não Entendida (gap)', 'Demanda Não Entendida (gap)'), ('Preço', 'Preço'), ('Enviado outra unidade AMBIPAR', 'Enviado outra unidade AMBIPAR'), ('Enviado para Repair', 'Enviado para Repair'), ('Enviado para C-safety', 'Enviado para C-safety'), ('Enviado para TDBR', 'Enviado para TDBR'), ('Enviado para PCTRs', 'Enviado para PCTRs'), ('Enviado para Portal Group', 'Enviado para Portal Group'), ('Técnica', 'Técnica'), ('N/A', 'N/A'), ('Escopo de Pequeno Porte', 'Escopo de Pequeno Porte'), ('Sem retorno', 'Sem retorno'), ('Inviabilidade operacional', 'Inviabilidade operacional'), ('Baixa Atratividade Comercial', 'Baixa Atratividade Comercial'), ('Critérios de habilitação', 'Critérios de habilitação')], max_length=100)),
                ('status_proposta', models.CharField(choices=[('Sem Retorno', 'Sem Retorno'), ('Em Análise', 'Em Análise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elaboração', 'Em Elaboração'), ('Declínio', 'Declínio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprovação gestores', 'Aguardando aprovação gestores')], max_length=50)),
                ('responsável', models.CharField(choices=[('Daniel Cunha', 'Daniel Cunha'), ('Rafael Pariz', 'Rafael Pariz'), ('Katlyn Brito', 'Katlyn Brito'), ('Sabryna Montoro', 'Sabrina Montoro'), ('Marcos França', 'Marcos França'), ('Felipe Segundo', 'Felipe Segundo'), ('Fernanda Braz', 'Fernanda Braz')], max_length=50)),
                ('comentário', models.TextField(blank=True, null=True)),
                ('requisitos_cliente', models.TextField(blank=True, null=True)),
                ('requisitos_ambipar', models.TextField(blank=True, null=True)),
                ('treinamentos', models.TextField()),
                ('ajuste_operacional', models.TextField()),
                ('analise_critica', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])),
                ('pt_financeiro', models.CharField(choices=[('Elaborada', 'Elaborada'), ('Pendente', 'Pendente'), ('Não Aplicável', 'Não Aplicável')], max_length=50)),
                ('pc_ptc', models.CharField(choices=[('Elaborado', 'Elaborado'), ('Pendente', 'Pendente'), ('Não Aplicável', 'Não Aplicável')], max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=10)),
                ('estimativo_receita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fonte_lead', models.CharField(choices=[('Portal Group', 'Portal Group'), ('Vendas Ambipar', 'Vendas Ambipar'), ('Cross Shell', 'Cross Shell'), ('Convite Direto', 'Convite Direto'), ('Prospecção Ativa', 'Prospecção Ativa')], max_length=50)),
                ('segmento_cliente', models.CharField(choices=[('Açúcar e Álcool', 'Açúcar e Álcool'), ('Administração Pública e Relacionados', 'Administração Pública e Relacionados'), ('Agronegócio', 'Agronegócio'), ('Água', 'Água'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recreação', 'Artes, cultura, esporte e recreação'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobiliárias', 'Atividades imobiliárias'), ('Automotivo, Aviação e Peças', 'Automotivo, Aviação e Peças'), ('Cimentícias', 'Cimentícias'), ('Comunicação', 'Comunicação'), ('Concessionárias', 'Concessionárias'), ('Condomínio', 'Condomínio'), ('Construção e Engenharia', 'Construção e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educação e Ensino', 'Educação e Ensino'), ('Eletroeletrônica', 'Eletroeletrônica'), ('Embalagens', 'Embalagens'), ('Embarcações e Apoio', 'Embarcações e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('Fábrica', 'Fábrica'), ('Farmacêutica/Saúde', 'Farmacêutica/Saúde'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gestão Ambiental', 'Gestão Ambiental'), ('Higiene/Cosméticos', 'Higiene/Cosméticos'), ('Hospitalar e Serviços Humanos', 'Hospitalar e Serviços Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informação e comunicação', 'Informação e comunicação'), ('Infraestrutura', 'Infraestrutura'), ('Instituições Financeiras', 'Instituições Financeiras'), ('Locadora', 'Locadora'), ('Logística', 'Logística'), ('Madeira', 'Madeira'), ('Manutenção e Reparação', 'Manutenção e Reparação'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos'), ('Material de construção', 'Material de construção'), ('Metal Mecânica/Metalurgia/Siderurgia', 'Metal Mecânica/Metalurgia/Siderurgia'), ('Mineração', 'Mineração'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organizações sem Fins Lucrativos', 'Organizações sem Fins Lucrativos'), ('Outras atividades de serviços', 'Outras atividades de serviços'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petróleo e Gás', 'Petróleo e Gás'), ('Plásticos e Borracha', 'Plásticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combustível', 'Postos de combustível'), ('Química e Petroquímica', 'Química e Petroquímica'), ('Saneamento/Resíduos', 'Saneamento/Resíduos'), ('Seguradoras', 'Seguradoras'), ('Serviços Ambientais', 'Serviços Ambientais'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços Pessoais', 'Serviços Pessoais'), ('Telecomunicações', 'Telecomunicações'), ('Têxtil, Couro e Vestuário', 'Têxtil, Couro e Vestuário'), ('Transporte Marítimo, Navegação ou Aquaviário', 'Transporte Marítimo, Navegação ou Aquaviário'), ('Transportes e Logística', 'Transportes e Logística'), ('Vidro', 'Vidro'), ('Marítmo', 'Marítmo')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_clientes', to='GO.ordemservico')),
                ('cordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_cordenadores', to='GO.ordemservico')),
                ('data_fim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_fim', to='GO.ordemservico')),
                ('data_fim_frente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_fim_frente', to='GO.ordemservico')),
                ('data_inicio_frente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_inicio_frente', to='GO.ordemservico')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_metodos', to='GO.ordemservico')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_pos', to='GO.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_servicos', to='GO.ordemservico')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_solicitantes', to='GO.ordemservico')),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_tipos_operacao', to='GO.ordemservico')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_unidades', to='GO.ordemservico')),
                ('volume_tanque_exec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_volume_tanques_exec', to='GO.rdotanque')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceiroCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='GO.financeiro')),
            ],
            options={
                'verbose_name': 'campo financeiro',
                'verbose_name_plural': 'campos financeiros',
                'ordering': ['id'],
            },
        ),
    ]
