# Generated by Django 4.2.23 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0187_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='houve_correcao',
            field=models.BooleanField(default=False),
        ),
    ]
