# Generated by Django 4.2.23 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0196_alter_financeiro_analise_critica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='houve_correcao',
            field=models.BooleanField(default=False),
        ),
    ]
