# Generated by Django 4.2.28 on 2026-07-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0162_migrar_responsaveis_coordenadores_legados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='responsavel',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='coordenador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
