# Generated by Django 4.2.28 on 2026-04-02 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0163_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAccessHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], db_index=True, max_length=16)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
                ('device_name', models.CharField(blank=True, max_length=120, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_access_heartbeats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Access Heartbeat',
                'verbose_name_plural': 'Supervisor Access Heartbeats',
                'ordering': ['-window_start', '-id'],
                'indexes': [models.Index(fields=['channel', 'window_start'], name='GO_supervis_channel_e1c6d3_idx'), models.Index(fields=['user', 'channel', 'window_start'], name='GO_supervis_user_id_808c36_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supervisoraccessheartbeat',
            constraint=models.UniqueConstraint(fields=('user', 'channel', 'window_start'), name='uniq_supervisor_access_heartbeat_window'),
        ),
    ]
