# Generated by Django 4.2.28 on 2026-04-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0164_supervisoraccessheartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDOChannelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], db_index=True, max_length=16)),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], db_index=True, max_length=16)),
                ('source_path', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdo_channel_events', to='GO.ordemservico')),
                ('rdo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_events', to='GO.rdo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdo_channel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDO Channel Event',
                'verbose_name_plural': 'RDO Channel Events',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['channel', 'event_type', 'occurred_at'], name='GO_rdochann_channel_ff0557_idx'), models.Index(fields=['user', 'channel', 'occurred_at'], name='GO_rdochann_user_id_3af1db_idx'), models.Index(fields=['rdo', 'channel', 'event_type'], name='GO_rdochann_rdo_id_ed71e8_idx')],
            },
        ),
    ]
