# Generated by Django 4.2.28 on 2026-05-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0170_rdo_data_analise_ia_rdo_erro_analise_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='data_pendente_analise_ia',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
