# Generated by Django 4.2.28 on 2026-06-03 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import GO.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0170_alter_ordemservico_servico_alter_rdo_servico_rdo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=GO.models.anexo_logistica_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_logistica_enviados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_logistica', to='GO.ordemservico')),
            ],
            options={
                'verbose_name': 'Anexo de Logística',
                'verbose_name_plural': 'Anexos de Logística',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
