# Generated by Django 4.2.28 on 2026-06-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0170_alter_ordemservico_servico_alter_rdo_servico_rdo_and_more'),
    ]

    # LogisticaAnexo was already introduced in 0170. Keep this migration as a
    # no-op checkpoint so existing databases retain a consistent graph while
    # fresh test databases do not try to create the same table twice.
    operations = []
