# Generated by Django 4.2.28 on 2026-06-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0171_rdo_data_pendente_analise_ia'),
        ('GO', '0176_rdo_retorno_equipamentos_and_previsto'),
    ]

    operations = [
    ]
