# Generated by Django 4.2.28 on 2026-06-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0178_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
