# Generated by Django 4.2.28 on 2026-06-22 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0180_alter_rdoatividade_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoEquipeOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_nome_snapshot', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Rascunho', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_equipe_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_equipe_criados', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_equipe', to='GO.ordemservico')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_equipe_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planejamento de Equipe da OS',
                'verbose_name_plural': 'Planejamentos de Equipe da OS',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoEquipeMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_snapshot', models.CharField(max_length=150)),
                ('funcao_planejada', models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('SUPERVISOR IRATA', 'SUPERVISOR IRATA'), ('ELETRICISTA', 'ELETRICISTA'), ('TÉCNICO DE SEGURANÇA', 'TÉCNICO DE SEGURANÇA'), ('AJUDANTE', 'AJUDANTE'), ('RESGATISTA', 'RESGATISTA'), ('MECÂNICO', 'MECÂNICO')], max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Substituído', 'Substituído'), ('Cancelado', 'Cancelado')], default='Ativo', max_length=20)),
                ('motivo_substituicao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_planejamento_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_planejamento_criados', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_equipe', to='GO.pessoa')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='GO.planejamentoequipeos')),
                ('substitui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutos', to='GO.planejamentoequipemembro')),
            ],
            options={
                'verbose_name': 'Membro Planejado',
                'verbose_name_plural': 'Membros Planejados',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
