# Generated by Django 4.2.28 on 2026-06-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0181_planejamentoequipeos_planejamentoequipemembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='data_prevista_subida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='horario_previsto_subida',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='local_subida',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='titulo_planejamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
