# Generated by Django 4.2.28 on 2026-06-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0182_planejamentoequipeos_data_prevista_subida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoEquipeHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('alteracao_cabecalho', 'Alteração de cabeçalho'), ('adicao_membro_pos_conclusao', 'Adição de membro após conclusão'), ('edicao_membro_pos_conclusao', 'Edição de membro após conclusão'), ('substituicao_membro_pos_conclusao', 'Substituição de membro após conclusão'), ('cancelamento_membro_pos_conclusao', 'Cancelamento de membro após conclusão')], max_length=80)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_planejamento_criados', to=settings.AUTH_USER_MODEL)),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='GO.planejamentoequipemembro')),
                ('planejamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='GO.planejamentoequipeos')),
            ],
            options={
                'verbose_name': 'Histórico de Planejamento de Equipe',
                'verbose_name_plural': 'Históricos de Planejamento de Equipe',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
