# Generated by Django 4.2.28 on 2026-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0183_planejamentoequipehistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentoequipemembro',
            name='data_desembarque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejamentoequipemembro',
            name='horario_desembarque',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planejamentoequipemembro',
            name='local_desembarque_membro',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='planejamentoequipemembro',
            name='observacao_desembarque',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='data_prevista_desembarque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='horario_previsto_desembarque',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='local_desembarque',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='planejamentoequipeos',
            name='observacao_desembarque',
            field=models.TextField(blank=True, default=''),
        ),
    ]
