# Generated by Django 4.2.28 on 2026-07-06 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0185_rdo_planejamento_equipe_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdomembroequipe',
            name='avaliacao_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='avaliacao_justificativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='avaliacao_nota',
            field=models.CharField(blank=True, choices=[('OTIMO', 'ÓTIMO'), ('BOM', 'BOM'), ('REGULAR', 'REGULAR'), ('RUIM', 'RUIM'), ('PESSIMO', 'PÉSSIMO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rdomembroequipe',
            name='avaliacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_rdo_membros', to=settings.AUTH_USER_MODEL),
        ),
    ]
