# Generated by Django 4.2.28 on 2026-07-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0186_rdomembroequipe_avaliacao_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('proposta', models.IntegerField(primary_key=True, serialize=False)),
                ('revisao', models.IntegerField()),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_solicitacao_proposta', models.DateField()),
                ('data_fechamento_proposta', models.DateField(blank=True, null=True)),
                ('previsao_contratacao', models.DateField()),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('natureza', models.CharField(choices=[('Aditivo, Reajuste, Spot, Contrato Novo', 'Aditivo, Reajuste, Spot, Contrato Novo'), ('Renova??o', 'Renova??o')], max_length=50)),
                ('heat_map', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('motivo_perda', models.CharField(choices=[('Governo', 'Governo'), ('Desist?ncia do cliente', 'Desist?ncia do cliente'), ('Fora do Escopo', 'Fora do Escopo'), ('Diretriz Estrat?gica', 'Diretriz Estrat?gica'), ('Prazo', 'Prazo'), ('Opera??es', 'Opera??es'), ('Demanda N?o Entendida (gap)', 'Demanda N?o Entendida (gap)'), ('Pre?o', 'Pre?o'), ('Enviado outra unidade AMBIPAR', 'Enviado outra unidade AMBIPAR'), ('Enviado para Repair', 'Enviado para Repair'), ('Enviado para C-safety', 'Enviado para C-safety'), ('Enviado para TDBR', 'Enviado para TDBR'), ('Enviado para PCTRs', 'Enviado para PCTRs'), ('Enviado para Portal Group', 'Enviado para Portal Group'), ('T?cnica', 'T?cnica'), ('N/A', 'N/A'), ('Escopo de Pequeno Porte', 'Escopo de Pequeno Porte'), ('Sem retorno', 'Sem retorno'), ('Inviabilidade operacional', 'Inviabilidade operacional'), ('Baixa Atratividade Comercial', 'Baixa Atratividade Comercial'), ('Crit?rios de habilita??o', 'Crit?rios de habilita??o')], max_length=100)),
                ('status_proposta', models.CharField(choices=[('Sem Retorno', 'Sem Retorno'), ('Em An?lise', 'Em An?lise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elabora??o', 'Em Elabora??o'), ('Decl?nio', 'Decl?nio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprova??o gestores', 'Aguardando aprova??o gestores')], max_length=50)),
                ('responsavel', models.CharField(choices=[('Daniel Cunha', 'Daniel Cunha'), ('Rafael Pariz', 'Rafael Pariz'), ('Katlyn Brito', 'Katlyn Brito'), ('Sabryna Montoro', 'Sabryna Montoro'), ('Marcos Fran?a', 'Marcos Fran?a'), ('Felipe Segundo', 'Felipe Segundo'), ('Fernanda Braz', 'Fernanda Braz')], max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('requisitos_cliente', models.TextField(blank=True, null=True)),
                ('requisitos_ambipar', models.TextField(blank=True, null=True)),
                ('treinamentos', models.TextField()),
                ('ajuste_operacional', models.TextField()),
                ('analise_critica', models.BooleanField(choices=[(True, 'Sim'), (False, 'N?o')])),
                ('pt_financeiro', models.CharField(choices=[('Elaborada', 'Elaborada'), ('Pendente', 'Pendente'), ('N?o Aplic?vel', 'N?o Aplic?vel')], max_length=50)),
                ('pc_ptc', models.CharField(choices=[('Elaborado', 'Elaborado'), ('Pendente', 'Pendente'), ('N?o Aplic?vel', 'N?o Aplic?vel')], max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=10)),
                ('estimativo_receita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fonte_lead', models.CharField(choices=[('Portal Group', 'Portal Group'), ('Vendas Ambipar', 'Vendas Ambipar'), ('Cross Shell', 'Cross Shell'), ('Convite Direto', 'Convite Direto'), ('Prospec??o Ativa', 'Prospec??o Ativa')], max_length=50)),
                ('segmento_cliente', models.CharField(choices=[('A??car e ?lcool', 'A??car e ?lcool'), ('Administra??o P?blica e Relacionados', 'Administra??o P?blica e Relacionados'), ('Agroneg?cio', 'Agroneg?cio'), ('?gua', '?gua'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recrea??o', 'Artes, cultura, esporte e recrea??o'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobili?rias', 'Atividades imobili?rias'), ('Automotivo, Avia??o e Pe?as', 'Automotivo, Avia??o e Pe?as'), ('Ciment?cias', 'Ciment?cias'), ('Comunica??o', 'Comunica??o'), ('Concession?rias', 'Concession?rias'), ('Condom?nio', 'Condom?nio'), ('Constru??o e Engenharia', 'Constru??o e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educa??o e Ensino', 'Educa??o e Ensino'), ('Eletroeletr?nica', 'Eletroeletr?nica'), ('Embalagens', 'Embalagens'), ('Embarca??es e Apoio', 'Embarca??es e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('F?brica', 'F?brica'), ('Farmac?utica/Sa?de', 'Farmac?utica/Sa?de'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gest?o Ambiental', 'Gest?o Ambiental'), ('Higiene/Cosm?ticos', 'Higiene/Cosm?ticos'), ('Hospitalar e Servi?os Humanos', 'Hospitalar e Servi?os Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informa??o e comunica??o', 'Informa??o e comunica??o'), ('Infraestrutura', 'Infraestrutura'), ('Institui??es Financeiras', 'Institui??es Financeiras'), ('Locadora', 'Locadora'), ('Log?stica', 'Log?stica'), ('Madeira', 'Madeira'), ('Manuten??o e Repara??o', 'Manuten??o e Repara??o'), ('M?quinas e Equipamentos', 'M?quinas e Equipamentos'), ('Material de constru??o', 'Material de constru??o'), ('Metal Mec?nica/Metalurgia/Siderurgia', 'Metal Mec?nica/Metalurgia/Siderurgia'), ('Minera??o', 'Minera??o'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organiza??es sem Fins Lucrativos', 'Organiza??es sem Fins Lucrativos'), ('Outras atividades de servi?os', 'Outras atividades de servi?os'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petr?leo e G?s', 'Petr?leo e G?s'), ('Pl?sticos e Borracha', 'Pl?sticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combust?vel', 'Postos de combust?vel'), ('Qu?mica e Petroqu?mica', 'Qu?mica e Petroqu?mica'), ('Saneamento/Res?duos', 'Saneamento/Res?duos'), ('Seguradoras', 'Seguradoras'), ('Servi?os Ambientais', 'Servi?os Ambientais'), ('Servi?os Dom?sticos', 'Servi?os Dom?sticos'), ('Servi?os Pessoais', 'Servi?os Pessoais'), ('Telecomunica??es', 'Telecomunica??es'), ('T?xtil, Couro e Vestu?rio', 'T?xtil, Couro e Vestu?rio'), ('Transporte Mar?timo, Navega??o ou Aquavi?rio', 'Transporte Mar?timo, Navega??o ou Aquavi?rio'), ('Transportes e Log?stica', 'Transportes e Log?stica'), ('Vidro', 'Vidro'), ('Mar?tmo', 'Mar?tmo')], max_length=50)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_disp_equipamentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_exaustor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_bomba_pneumatica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_painel_eletrico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_luminarias_eletricas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_luminarias_pneumaticas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_ar_condicionado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_compressor_ar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_tank_scope', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_kit_resgate1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_kit_resgate2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa5', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa6', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_clientes', to='GO.ordemservico')),
                ('cordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_cordenadores', to='GO.ordemservico')),
                ('data_fim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_fim', to='GO.ordemservico')),
                ('data_fim_frente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_fim_frente', to='GO.ordemservico')),
                ('data_inicio_frente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_datas_inicio_frente', to='GO.ordemservico')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_metodos', to='GO.ordemservico')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_pos', to='GO.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_servicos', to='GO.ordemservico')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_solicitantes', to='GO.ordemservico')),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_tipos_operacao', to='GO.ordemservico')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_unidades', to='GO.ordemservico')),
                ('volume_tanque_exec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financeiro_volume_tanques_exec', to='GO.rdotanque')),
            ],
            options={
                'ordering': ['-proposta'],
            },
        ),
    ]
