# Generated by Django 4.2.28 on 2026-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0187_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='data_entrega_proposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='tempo_contrato_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='analise_critica',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Nao')]),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='motivo_perda',
            field=models.CharField(choices=[('Governo', 'Governo'), ('Desist?ncia do cliente', 'Desist?ncia do cliente'), ('Fora do Escopo', 'Fora do Escopo'), ('Diretriz Estrat?gica', 'Diretriz Estrat?gica'), ('Prazo', 'Prazo'), ('Opera??es', 'Opera??es'), ('Demanda N?o Entendida (gap)', 'Demanda N?o Entendida (gap)'), ('Pre?o', 'Pre?o'), ('Enviado outra unidade AMBIPAR', 'Enviado outra unidade AMBIPAR'), ('Enviado para Repair', 'Enviado para Repair'), ('Enviado para C-safety', 'Enviado para C-safety'), ('Enviado para TDBR', 'Enviado para TDBR'), ('Enviado para PCTRs', 'Enviado para PCTRs'), ('Enviado para Portal Group', 'Enviado para Portal Group'), ('T?cnica', 'T?cnica'), ('N/A', 'N/A'), ('Escopo de Pequeno Porte', 'Escopo de Pequeno Porte'), ('Sem retorno', 'Sem retorno'), ('Inviabilidade operacional', 'Inviabilidade operacional'), ('Baixa Atratividade Comercial', 'Baixa Atratividade Comercial'), ('Criterios de habilitacao', 'Criterios de habilitacao')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='pc_ptc',
            field=models.CharField(choices=[('Elaborado', 'Elaborado'), ('Pendente', 'Pendente'), ('Nao Aplicavel', 'Nao Aplicavel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='pt_financeiro',
            field=models.CharField(choices=[('Elaborada', 'Elaborada'), ('Pendente', 'Pendente'), ('Nao Aplicavel', 'Nao Aplicavel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='responsavel',
            field=models.CharField(choices=[('Daniel Cunha', 'Daniel Cunha'), ('Rafael Pariz', 'Rafael Pariz'), ('Katlyn Brito', 'Katlyn Brito'), ('Sabryna Montoro', 'Sabryna Montoro'), ('Marcos Franca', 'Marcos Franca'), ('Felipe Segundo', 'Felipe Segundo'), ('Fernanda Braz', 'Fernanda Braz')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='segmento_cliente',
            field=models.CharField(choices=[('Açucar e alcool', 'Açucar e alcool'), ('Administ  racao Publica e Relacionados', 'Administracao Publica e Relacionados'), ('Agronegocio', 'Agronegocio'), ('Agua', 'Agua'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recreacao', 'Artes, cultura, esporte e recreacao'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobiliarias', 'Atividades imobiliarias'), ('Automotivo, Aviaçao e Peças', 'Automotivo, Aviaçao e Peças'), ('Cimenticias', 'Cimenticias'), ('Comunicacao', 'Comunicacao'), ('Concessionarias', 'Concessionarias'), ('Condominio', 'Condominio'), ('Construção e Engenharia', 'Construção e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educação e Ensino', 'Educação e Ensino'), ('Eletroeletrônica', 'Eletroeletrônica'), ('Embalagens', 'Embalagens'), ('Embarcações e Apoio', 'Embarcações e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('Fábrica', 'Fábrica'), ('Farmacêutica/Saúde', 'Farmacêutica/Saúde'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gestão Ambiental', 'Gestão Ambiental'), ('Higiene/Cosméticos', 'Higiene/Cosméticos'), ('Hospitalar e Serviços Humanos', 'Hospitalar e Serviços Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informação e comunicação', 'Informação e comunicação'), ('Infraestrutura', 'Infraestrutura'), ('Instituições Financeiras  ', 'Instituições Financeiras'), ('Locadora', 'Locadora'), ('Logística', 'Logística'), ('Madeira', 'Madeira'), ('Manutenção e Reparação', 'Manutenção e Reparação'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos'), ('Material de construção', 'Material de construção'), ('Metal Mecânica/Metalurgia/Siderurgia', 'Metal Mecânica/Metalurgia/Siderurgia'), ('Mineração', 'Mineração'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organizações sem Fins Lucrativos', 'Organizações sem Fins Lucrativos'), ('Outras atividades de serviços', 'Outras atividades de serviços'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petróleo e Gás', 'Petróleo e Gás'), ('Plásticos e Borracha', 'Plásticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combustível', 'Postos de combustível'), ('Química e Petroquímica', 'Química e Petroquímica'), ('Saneamento/Resíduos', 'Saneamento/Resíduos'), ('Seguradoras', 'Seguradoras'), ('Serviços Ambientais', 'Serviços Ambientais'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços Pessoais', 'Serviços Pessoais'), ('Telecomunicações', 'Telecomunicações'), ('Têxtil, Couro e Vestuário', 'T?xtil, Couro e Vestu?rio'), ('Transporte Marítimo, Navegação ou Aquaviário', 'Transporte Marítimo, Navegação ou Aquaviário'), ('Transportes e Logística', 'Transportes e Log?stica'), ('Vidro', 'Vidro'), ('Marítmo', 'Marítmo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='status_proposta',
            field=models.CharField(choices=[('Sem Retorno', 'Sem Retorno'), ('Em An?lise', 'Em An?lise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elaboracao', 'Em Elaboracao'), ('Declinio', 'Declinio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprovacao gestores', 'Aguardando aprovacao gestores')], max_length=50),
        ),
    ]
