# Generated by Django 4.2.28 on 2026-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0189_financeirocampo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='motivo_perda',
            field=models.CharField(choices=[('Governo', 'Governo'), ('Desistência do cliente', 'Desistência do cliente'), ('Fora do Escopo', 'Fora do Escopo'), ('Diretriz Estratégica', 'Diretriz Estratégica'), ('Prazo', 'Prazo'), ('Operações', 'Operações'), ('Demanda Não Entendida (gap)', 'Demanda Não Entendida (gap)'), ('Preço', 'Preço'), ('Enviado outra unidade AMBIPAR', 'Enviado outra unidade AMBIPAR'), ('Enviado para Repair', 'Enviado para Repair'), ('Enviado para C-safety', 'Enviado para C-safety'), ('Enviado para TDBR', 'Enviado para TDBR'), ('Enviado para PCTRs', 'Enviado para PCTRs'), ('Enviado para Portal Group', 'Enviado para Portal Group'), ('Técnica', 'Técnica'), ('N/A', 'N/A'), ('Escopo de Pequeno Porte', 'Escopo de Pequeno Porte'), ('Sem retorno', 'Sem retorno'), ('Inviabilidade operacional', 'Inviabilidade operacional'), ('Baixa Atratividade Comercial', 'Baixa Atratividade Comercial'), ('Critérios de habilitação', 'Critérios de habilitação')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='natureza',
            field=models.CharField(choices=[('Aditivo, Reajuste, Spot, Contrato Novo', 'Aditivo, Reajuste, Spot, Contrato Novo'), ('Renovação', 'Renovação')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='status_proposta',
            field=models.CharField(choices=[('Sem Retorno', 'Sem Retorno'), ('Em Análise', 'Em Análise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elaboracao', 'Em Elaboracao'), ('Declinio', 'Declinio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprovacao gestores', 'Aguardando aprovacao gestores')], max_length=50),
        ),
    ]
