# Generated by Django 4.2.28 on 2026-07-16 13:04

from django.db import migrations, models
from GO.models import OrdemServico


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0190_alter_financeiro_motivo_perda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='servico',
            field=models.CharField(blank=True, choices=OrdemServico.SERVICO_CHOICES, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='solicitante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
