# Generated by Django 4.2.28 on 2026-07-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0191_alter_financeiro_fonte_lead_alter_financeiro_po_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='fonte_lead',
            field=models.CharField(choices=[('Portal Group', 'Portal Group'), ('Vendas Ambipar', 'Vendas Ambipar'), ('Cross Shell', 'Cross Shell'), ('Convite Direto', 'Convite Direto'), ('Prospecão Ativa', 'Prospecão Ativa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='segmento_cliente',
            field=models.CharField(choices=[('Açucar e alcool', 'Açucar e alcool'), ('Administração Pública e Relacionados', 'Administração Pública e Relacionados'), ('Agronegócio', 'Agronegócio'), ('Agua', 'Agua'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recreacao', 'Artes, cultura, esporte e recreacao'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobiliarias', 'Atividades imobiliarias'), ('Automotivo, Aviaçao e Peças', 'Automotivo, Aviaçao e Peças'), ('Cimenticias', 'Cimenticias'), ('Comunicacao', 'Comunicacao'), ('Concessionarias', 'Concessionarias'), ('Condominio', 'Condominio'), ('Construção e Engenharia', 'Construção e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educação e Ensino', 'Educação e Ensino'), ('Eletroeletrônica', 'Eletroeletrônica'), ('Embalagens', 'Embalagens'), ('Embarcações e Apoio', 'Embarcações e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('Fábrica', 'Fábrica'), ('Farmacêutica/Saúde', 'Farmacêutica/Saúde'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gestão Ambiental', 'Gestão Ambiental'), ('Higiene/Cosméticos', 'Higiene/Cosméticos'), ('Hospitalar e Serviços Humanos', 'Hospitalar e Serviços Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informação e comunicação', 'Informação e comunicação'), ('Infraestrutura', 'Infraestrutura'), ('Instituições Financeiras  ', 'Instituições Financeiras'), ('Locadora', 'Locadora'), ('Logística', 'Logística'), ('Madeira', 'Madeira'), ('Manutenção e Reparação', 'Manutenção e Reparação'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos'), ('Material de construção', 'Material de construção'), ('Metal Mecânica/Metalurgia/Siderurgia', 'Metal Mecânica/Metalurgia/Siderurgia'), ('Mineração', 'Mineração'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organizações sem Fins Lucrativos', 'Organizações sem Fins Lucrativos'), ('Outras atividades de serviços', 'Outras atividades de serviços'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petróleo e Gás', 'Petróleo e Gás'), ('Plásticos e Borracha', 'Plásticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combustível', 'Postos de combustível'), ('Química e Petroquímica', 'Química e Petroquímica'), ('Saneamento/Resíduos', 'Saneamento/Resíduos'), ('Seguradoras', 'Seguradoras'), ('Serviços Ambientais', 'Serviços Ambientais'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços Pessoais', 'Serviços Pessoais'), ('Telecomunicações', 'Telecomunicações'), ('Têxtil, Couro e Vestuário', 'Têxtil, Couro e Vestuário'), ('Transporte Marítimo, Navegação ou Aquaviário', 'Transporte Marítimo, Navegação ou Aquaviário'), ('Transportes e Logística', 'Transportes e Logística'), ('Vidro', 'Vidro'), ('Marítmo', 'Marítmo')], max_length=50),
        ),
    ]
