# Generated by Django 4.2.28 on 2026-07-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0192_alter_financeiro_fonte_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa1',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa2',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa3',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa4',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa5',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='taxa6',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_ar_condicionado',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_bomba_pneumatica',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_compressor_ar',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_disp_equipamentos',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_exaustor',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_kit_resgate1',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_kit_resgate2',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_limpeza',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_luminarias_eletricas',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_luminarias_pneumaticas',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_painel_eletrico',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_tank_scope',
        ),
    ]
