# Generated by Django 4.2.28 on 2026-07-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0187_alter_ordemservico_servico_alter_rdo_servico_rdo'),
        ('GO', '0194_financeirocampo_preco_unitario_quantidade_subtotal'),
    ]

    operations = [
    ]
