# Generated by Django 4.2.28 on 2026-07-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0195_merge_20260721_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='analise_critica',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')]),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='fonte_lead',
            field=models.CharField(choices=[('Portal Group', 'Portal Group'), ('Vendas Ambipar', 'Vendas Ambipar'), ('Cross Shell', 'Cross Shell'), ('Convite Direto', 'Convite Direto'), ('Prospecção Ativa', 'Prospecção Ativa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('Governo', 'Governo'), ('Desistência do cliente', 'Desistência do cliente'), ('Fora do Escopo', 'Fora do Escopo'), ('Diretriz Estratégica', 'Diretriz Estratégica'), ('Prazo', 'Prazo'), ('Operações', 'Operações'), ('Demanda Não Entendida (gap)', 'Demanda Não Entendida (gap)'), ('Preço', 'Preço'), ('Enviado outra unidade AMBIPAR', 'Enviado outra unidade AMBIPAR'), ('Enviado para Repair', 'Enviado para Repair'), ('Enviado para C-safety', 'Enviado para C-safety'), ('Enviado para TDBR', 'Enviado para TDBR'), ('Enviado para PCTRs', 'Enviado para PCTRs'), ('Enviado para Portal Group', 'Enviado para Portal Group'), ('Técnica', 'Técnica'), ('N/A', 'N/A'), ('Escopo de Pequeno Porte', 'Escopo de Pequeno Porte'), ('Sem retorno', 'Sem retorno'), ('Inviabilidade operacional', 'Inviabilidade operacional'), ('Baixa Atratividade Comercial', 'Baixa Atratividade Comercial'), ('Critérios de habilitação', 'Critérios de habilitação')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='natureza',
            field=models.CharField(choices=[('Aditivo', 'Aditivo'), ('Reajuste', 'Reajuste'), ('Spot', 'Spot'), ('Contrato Novo', 'Contrato Novo'), ('Renovação', 'Renovação')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='pc_ptc',
            field=models.CharField(choices=[('Elaborado', 'Elaborado'), ('Pendente', 'Pendente'), ('Não Aplicável', 'Não Aplicável')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='pt_financeiro',
            field=models.CharField(choices=[('Elaborada', 'Elaborada'), ('Pendente', 'Pendente'), ('Não Aplicável', 'Não Aplicável')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='segmento_cliente',
            field=models.CharField(choices=[('Açúcar e Álcool', 'Açúcar e Álcool'), ('Administração Pública e Relacionados', 'Administração Pública e Relacionados'), ('Agronegócio', 'Agronegócio'), ('Água', 'Água'), ('Alimentos e Bebidas', 'Alimentos e Bebidas'), ('Artes, cultura, esporte e recreação', 'Artes, cultura, esporte e recreação'), ('Atacado e Varejo', 'Atacado e Varejo'), ('Atividades administrativas e Relacionados', 'Atividades administrativas e Relacionados'), ('Atividades imobiliárias', 'Atividades imobiliárias'), ('Automotivo, Aviação e Peças', 'Automotivo, Aviação e Peças'), ('Cimentícias', 'Cimentícias'), ('Comunicação', 'Comunicação'), ('Concessionárias', 'Concessionárias'), ('Condomínio', 'Condomínio'), ('Construção e Engenharia', 'Construção e Engenharia'), ('Consultoria e Atividades Profissionais', 'Consultoria e Atividades Profissionais'), ('Data Center', 'Data Center'), ('Educação e Ensino', 'Educação e Ensino'), ('Eletroeletrônica', 'Eletroeletrônica'), ('Embalagens', 'Embalagens'), ('Embarcações e Apoio', 'Embarcações e Apoio'), ('Energia', 'Energia'), ('Eventos', 'Eventos'), ('Fábrica', 'Fábrica'), ('Farmacêutica/Saúde', 'Farmacêutica/Saúde'), ('Ferrovias', 'Ferrovias'), ('Fertilizantes', 'Fertilizantes'), ('Gestão Ambiental', 'Gestão Ambiental'), ('Higiene/Cosméticos', 'Higiene/Cosméticos'), ('Hospitalar e Serviços Humanos', 'Hospitalar e Serviços Humanos'), ('Hoteis/Pousadas', 'Hoteis/Pousadas'), ('Informação e comunicação', 'Informação e comunicação'), ('Infraestrutura', 'Infraestrutura'), ('Instituições Financeiras', 'Instituições Financeiras'), ('Locadora', 'Locadora'), ('Logística', 'Logística'), ('Madeira', 'Madeira'), ('Manutenção e Reparação', 'Manutenção e Reparação'), ('Máquinas e Equipamentos', 'Máquinas e Equipamentos'), ('Material de construção', 'Material de construção'), ('Metal Mecânica/Metalurgia/Siderurgia', 'Metal Mecânica/Metalurgia/Siderurgia'), ('Mineração', 'Mineração'), ('Organismos Internacionais', 'Organismos Internacionais'), ('Organizações sem Fins Lucrativos', 'Organizações sem Fins Lucrativos'), ('Outras atividades de serviços', 'Outras atividades de serviços'), ('Outros', 'Outros'), ('Papel e Celulose', 'Papel e Celulose'), ('Petróleo e Gás', 'Petróleo e Gás'), ('Plásticos e Borracha', 'Plásticos e Borracha'), ('Portos e Terminais', 'Portos e Terminais'), ('Postos de combustível', 'Postos de combustível'), ('Química e Petroquímica', 'Química e Petroquímica'), ('Saneamento/Resíduos', 'Saneamento/Resíduos'), ('Seguradoras', 'Seguradoras'), ('Serviços Ambientais', 'Serviços Ambientais'), ('Serviços Domésticos', 'Serviços Domésticos'), ('Serviços Pessoais', 'Serviços Pessoais'), ('Telecomunicações', 'Telecomunicações'), ('Têxtil, Couro e Vestuário', 'Têxtil, Couro e Vestuário'), ('Transporte Marítimo, Navegação ou Aquaviário', 'Transporte Marítimo, Navegação ou Aquaviário'), ('Transportes e Logística', 'Transportes e Logística'), ('Vidro', 'Vidro'), ('Marítmo', 'Marítmo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='status_proposta',
            field=models.CharField(choices=[('Sem Retorno', 'Sem Retorno'), ('Em Análise', 'Em Análise'), ('ShortList', 'ShortList'), ('Revisada', 'Revisada'), ('Perdida/Recusada', 'Perdida/Recusada'), ('Fechada/Contratada', 'Fechada/Contratada'), ('Cancelada', 'Cancelada'), ('Em Elaboração', 'Em Elaboração'), ('Declínio', 'Declínio'), ('Avaliando escopo', 'Avaliando escopo'), ('Aguardando aprovação gestores', 'Aguardando aprovação gestores'), ('Enviada', 'Enviada'), ('Em Negociação', 'Em Negociação')], max_length=50),
        ),
    ]
