# Generated by Django 4.2.28 on 2026-07-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0164_adicionar_responsaveis_comerciais_iniciais'),
        ('GO', '0196_alter_financeiro_analise_critica_and_more'),
    ]

    operations = [
    ]
