# Generated by Django 4.2.28 on 2026-07-29 13:38

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0198_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='cliente_nome_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='unidade_nome_ci_unique'),
        ),
    ]
