# Generated by Django 4.2.28 on 2026-07-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0199_cliente_cliente_nome_ci_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='email_solicitante',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='telefone_solicitante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
