# Generated by Django 4.2.28 on 2026-07-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import re


DEFAULT_METHODS = ('Manual', 'Mecanizada', 'Robotizada', 'N/A')


def seed_commercial_methods(apps, schema_editor):
    MetodoOperacional = apps.get_model('GO', 'MetodoOperacional')
    OrdemServico = apps.get_model('GO', 'OrdemServico')
    Financeiro = apps.get_model('GO', 'Financeiro')

    def normalize(value):
        return re.sub(r'\s+', ' ', str(value or '')).strip()

    methods_by_key = {}
    source_values = list(DEFAULT_METHODS)
    source_values.extend(OrdemServico.objects.exclude(metodo__isnull=True).values_list('metodo', flat=True).distinct())

    for raw_name in source_values:
        name = normalize(raw_name)
        if not name:
            continue
        key = name.casefold()
        method = methods_by_key.get(key)
        if method is None:
            method = MetodoOperacional.objects.filter(nome__iexact=name).first()
        if method is None:
            method = MetodoOperacional.objects.create(nome=name)
        methods_by_key[key] = method

    for proposal in Financeiro.objects.select_related('metodo').all():
        legacy_method = normalize(getattr(proposal.metodo, 'metodo', ''))
        if not legacy_method:
            continue
        method = methods_by_key.get(legacy_method.casefold())
        if method is not None:
            proposal.metodo_cadastro_id = method.pk
            proposal.save(update_fields=['metodo_cadastro'])


def reverse_seed_commercial_methods(apps, schema_editor):
    # The schema rollback removes the catalog; legacy Financeiro.metodo stays untouched.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0200_financeiro_email_solicitante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'método operacional',
                'verbose_name_plural': 'métodos operacionais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='metodooperacional',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='metodo_operacional_nome_ci_unique'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='metodo_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_comerciais', to='GO.metodooperacional'),
        ),
        migrations.RunPython(seed_commercial_methods, reverse_seed_commercial_methods),
    ]
