# Generated by Django 4.2.28 on 2026-07-31 13:01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0202_alter_ordemservico_servico_alter_rdo_servico_rdo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEquipamentoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item ou equipamento comercial',
                'verbose_name_plural': 'itens e equipamentos comerciais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'serviço comercial',
                'verbose_name_plural': 'serviços comerciais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicocomercial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='servico_comercial_nome_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemequipamentocomercial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='item_equipamento_comercial_nome_ci_unique'),
        ),
    ]
