# Generated by Django 4.2.28 on 2026-07-31 13:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0203_itemequipamentocomercial_servicocomercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoClienteComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'segmento de cliente comercial',
                'verbose_name_plural': 'segmentos de clientes comerciais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='segmentoclientecomercial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='segmento_cliente_comercial_nome_ci_unique'),
        ),
    ]
