# Generated by Django 4.2.28 on 2026-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0204_segmentoclientecomercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='rfi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
