# Generated by Django 4.2.28 on 2026-08-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_legacy_critical_analysis(apps, schema_editor):
    Financeiro = apps.get_model('GO', 'Financeiro')
    AnaliseCriticaOportunidade = apps.get_model('GO', 'AnaliseCriticaOportunidade')

    for proposal in Financeiro.objects.filter(analise_critica=True).iterator():
        AnaliseCriticaOportunidade.objects.get_or_create(
            proposta=proposal,
            defaults={'status_legado_realizada': True},
        )
        # Completion now depends exclusively on the fourteen individual answers.
        Financeiro.objects.filter(pk=proposal.pk).update(analise_critica=False)


def reverse_migrate_legacy_critical_analysis(apps, schema_editor):
    Financeiro = apps.get_model('GO', 'Financeiro')
    AnaliseCriticaOportunidade = apps.get_model('GO', 'AnaliseCriticaOportunidade')
    for analysis in AnaliseCriticaOportunidade.objects.filter(status_legado_realizada=True).iterator():
        Financeiro.objects.filter(pk=analysis.proposta_id).update(analise_critica=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GO', '0205_financeiro_rfi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCriticaOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_atender_requisitos', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('habilitacao_tecnica_atendida', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('visita_tecnica_necessaria', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('escopo_claramente_definido', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('competencia_tecnica_execucao', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('recursos_disponiveis', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('equipe_com_treinamentos', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('equipe_irata_disponivel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('equipe_resgate_disponivel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('tempo_habil_mobilizacao', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('tempo_habil_aquisicao', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('riscos_comerciais_relevantes', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('oportunidade_viavel_rentavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('pendencias_financeiras_cliente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não aplicável')], max_length=3, null=True)),
                ('comentario', models.TextField(blank=True, default='')),
                ('status_legado_realizada', models.BooleanField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_criticas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_criticas_criadas', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_critica_oportunidade', to='GO.financeiro')),
            ],
            options={
                'verbose_name': 'análise crítica da oportunidade',
                'verbose_name_plural': 'análises críticas da oportunidade',
            },
        ),
        migrations.RunPython(migrate_legacy_critical_analysis, reverse_migrate_legacy_critical_analysis),
    ]
