# Generated by Django 4.2.28 on 2026-08-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0198_rdo_aprovado_rdo_aprovado_em_rdo_aprovado_por'),
        ('GO', '0205_financeiro_rfi'),
    ]

    operations = [
    ]
