# Generated by Django 4.2.28 on 2026-08-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0206_analisecriticaoportunidade'),
        ('GO', '0206_merge_20260804_1929'),
    ]

    operations = [
    ]
